import Mathlib
import Orbits.Reference

/-!
# orbits: contract

What the outputs of `Reference.lean` mean in Mathlib's terms. As in `Gfp.Contract`, these are
stated obligations, not discharged proofs: the native backends are checked against
`Reference.lean` by `decide`, and `Reference.lean` is related to Mathlib here.

The group is the subgroup of `Equiv.Perm (Fin N)` (for `N` the number of members) generated by
the index maps of the generators; every statement below is about the orbits of that subgroup.
-/

namespace Orbits.Contract

open Gfp

/-- The index map of generator `k`: member `i` goes to the member equal to its image. -/
def indexMap (g : Group) (f : Gfp.Family) (k i : ℕ) : ℕ :=
  let ks := keys g f
  ks.idxOf (image g f k (ks.getD i []))

/-- Each generator permutes the member indices. -/
theorem indexMap_bijective (g : Group) (f : Gfp.Family) (hg : actsOn g f = true) (k : ℕ) (hk : k < g.size) :
    Set.BijOn (indexMap g f k) (Set.Iio (keys g f).length) (Set.Iio (keys g f).length) := by
  sorry

/-- The group generated inside `Equiv.Perm (Fin N)`; `sorry` stands for the transport of
`indexMap` to a permutation, which `indexMap_bijective` licenses. -/
noncomputable def indexGroup (g : Group) (f : Gfp.Family) : Subgroup (Equiv.Perm (Fin (keys g f).length)) :=
  sorry

/-- `orbit g f i` lists exactly the orbit of `i` under the index group, without repetition. -/
theorem orbit_spec (g : Group) (f : Gfp.Family) (hg : actsOn g f = true) (i : ℕ) (hi : i < (keys g f).length) :
    (orbit g f i).Nodup ∧
    ∀ j, j ∈ orbit g f i ↔ ∃ hj : j < (keys g f).length,
      (⟨j, hj⟩ : Fin _) ∈ MulAction.orbit (indexGroup g f) (⟨i, hi⟩ : Fin _) := by
  sorry

/-- `is_canonical` with `count` is the number of orbits. -/
theorem isCanonical_count (g : Group) (f : Gfp.Family) (hg : actsOn g f = true) :
    run (.isCanonical g) (.gfp f) .count =
      .count (Nat.card (MulAction.orbitRel.Quotient (indexGroup g f) (Fin (keys g f).length))) (keys g f).length := by
  sorry

/-- `stabilizer_order` is the order of the stabiliser in the *abstract* group given by the
generators, which equals `|G| / |orbit|` by orbit-stabiliser. -/
theorem stabilizerOrder_spec (g : Group) (f : Gfp.Family) (hg : actsOn g f = true) (i : ℕ) (hi : i < (keys g f).length) :
    (orbit g f i).length * (g.order / (orbit g f i).length) = g.order := by
  sorry

/-- Cauchy-Frobenius: the fixed-point counts over the group sum to `|G|` times the number of orbits.
Stated for permutation groups on subsets, which is where `fixed_points` is defined. -/
theorem burnside (gens : List Perm) (p : ℕ) (d : List Vec) (k : ℕ) (h : gens.all (·.length = d.length) = true) :
    ∀ xs c N, run (.fixedPoints (.subsets p d k)) (.groupElements gens) .all = .integers xs →
      run (.isCanonical (.perms gens)) (.gfp (.subsets p d k)) .count = .count c N →
      xs.sum = (permElements gens).length * c := by
  sorry

/-- `permElements` is the generated subgroup of `Equiv.Perm (Fin n)`, each element once. -/
theorem permElements_spec (gens : List Perm) (n : ℕ) (h : gens.all (·.length = n) = true) :
    (permElements gens).Nodup ∧ (permElements gens).length = Nat.card (Subgroup.closure
      {σ : Equiv.Perm (Fin n) | ∃ g ∈ gens, ∀ i : Fin n, (σ i : ℕ) = g.getD i 0}) := by
  sorry

/-- The projective action is the permutation of the listed points induced by `v ↦ v A`, when the
points are a set of normalised representatives closed under every `A`. -/
theorem projectiveAction_spec (p : ℕ) [Fact p.Prime] (batch : List Mat) (pts : List Vec) (ps : List Perm)
    (hpts : ∀ v ∈ pts, normalise p v = v) (hnodup : pts.Nodup)
    (hclosed : ∀ a ∈ batch, ∀ v ∈ pts, normalise p ((matmul p [v] a).headD []) ∈ pts) :
    run (.projectiveAction pts) (.gfp (.explicit p batch)) .all = .perms ps →
      ∀ i a, i < batch.length → batch.getD i [] = a → ∀ j, j < pts.length →
        pts.getD ((ps.getD i []).getD j 0) [] = normalise p ((matmul p [pts.getD j []] a).headD []) := by
  sorry

end Orbits.Contract
