import Gfp.Reference

/-!
# orbits: executable reference

A group given by generators acts on a family by permuting its member indices; the canonical
representative of an orbit is the member with the least index, in the order `Gfp.Reference`
defines for the family. Orbits are computed by saturating under the generators, groups by
saturating under multiplication. Everything is plain structural recursion so that
`decide +kernel` can evaluate it; a kernel answer is correct when
`example : run op family red = answer := by decide` is accepted.

A permutation of `n` points is a list of `n` images. Generators of a matrix group are `n x n`
matrices over `F_p`; they act on the right (`M ↦ M A`), on Grassmannian members up to rref.
-/

namespace Orbits

open Gfp (Vec Mat)

abbrev Perm := List Nat

/-- `x ↦ h (g x)`. -/
def compose (g h : Perm) : Perm := g.map fun x => h.getD x 0

def identityPerm (n : Nat) : Perm := List.range n

/-- Insertion sort by a Boolean order. -/
def insertBy (le : α → α → Bool) (x : α) : List α → List α
  | [] => [x]
  | y :: ys => if le x y then x :: y :: ys else y :: insertBy le x ys

def sortBy (le : α → α → Bool) (xs : List α) : List α := xs.foldr (insertBy le) []

def lexLe : List Nat → List Nat → Bool
  | [], _ => true
  | _ :: _, [] => false
  | x :: xs, y :: ys => if x < y then true else if y < x then false else lexLe xs ys

/-- Close `acc` under `step`, one breadth-first layer per unit of fuel, stopping at a fixpoint. -/
def saturate [DecidableEq α] (step : α → List α) : Nat → List α → List α
  | 0, acc => acc
  | fuel + 1, acc =>
    let next := acc.foldl (fun s a => (step a).foldl (fun s b => if b ∈ s then s else s ++ [b]) s) acc
    if next.length = acc.length then acc else saturate step fuel next

/-- Enough layers for any group or orbit a test will ask about. -/
def fuel : Nat := 1 <<< 26

/-- Every element of the permutation group generated by `gens`, lexicographic by image list. -/
def permElements (gens : List Perm) : List Perm :=
  let n := (gens.headD []).length
  sortBy lexLe (saturate (fun g => gens.map (compose g)) fuel [identityPerm n])

def matElements (p : Nat) (gens : List Mat) : List Mat :=
  let n := (gens.headD []).length
  saturate (fun a => gens.map (Gfp.matmul p a)) fuel [Gfp.identity n]

/-! ## Actions -/

/-- A permutation of dictionary positions acting on a subset given by its sorted positions, each
position written as a one-entry row so that subsets and matrices share the `Mat` type. -/
def actPerm (g : Perm) (m : Mat) : Mat :=
  (sortBy (· ≤ ·) (m.map fun row => g.getD (row.headD 0) 0)).map ([·])

/-- Positions of a `subsets` member, in the family's order. -/
def subsetKeys (d : List Vec) (k : Nat) : List Mat := (Gfp.combos (List.range d.length) k).map (·.map ([·]))

inductive Group
  | perms (gens : List Perm)
  | mats (p : Nat) (gens : List Mat)

def Group.size : Group → Nat
  | .perms gens => gens.length
  | .mats _ gens => gens.length

def Group.order : Group → Nat
  | .perms gens => (permElements gens).length
  | .mats p gens => (matElements p gens).length

/-- Whether the group's generators act on the family at all. -/
def actsOn : Group → Gfp.Family → Bool
  | .perms gens, .subsets _ d _ => gens.all fun g => g.length = d.length
  | .mats p gens, .grassmannian p' n _ => p = p' ∧ gens.all fun a => a.length = n ∧ a.all (·.length = n)
  | .mats p gens, .allMatrices p' _ n => p = p' ∧ gens.all fun a => a.length = n ∧ a.all (·.length = n)
  | _, _ => false

/-- What the group permutes: subset members as their dictionary positions (so that duplicate
dictionary rows remain distinct members), matrix family members as themselves. -/
def keys : Group → Gfp.Family → List Mat
  | .perms _, .subsets _ d k => subsetKeys d k
  | _, f => f.members

/-- Image of key `m` under generator `k`, canonicalised within the family. -/
def image (g : Group) (f : Gfp.Family) (k : Nat) (m : Mat) : Mat :=
  match g, f with
  | .perms gens, .subsets _ _ _ => actPerm (gens.getD k []) m
  | .mats p gens, .grassmannian _ _ _ => Gfp.rref p (Gfp.matmul p m (gens.getD k []))
  | .mats p gens, _ => Gfp.matmul p m (gens.getD k [])
  | _, _ => m

/-- Indices of the orbit of member `i`. -/
def orbit (g : Group) (f : Gfp.Family) (i : Nat) : List Nat :=
  let ks := keys g f
  saturate (fun j => (List.range g.size).map fun k => ks.idxOf (image g f k (ks.getD j []))) fuel [i]

def leastOf (xs : List Nat) : Nat := xs.foldl min (xs.headD 0)

/-- Scale a nonzero vector so its first nonzero entry is 1. -/
def normalise (p : Nat) (v : Vec) : Vec :=
  match v.find? (· ≠ 0) with
  | some a => Gfp.scale p v (Gfp.inv p a)
  | none => v

/-! ## Families, operations, reductions, results -/

inductive Family
  | gfp (f : Gfp.Family)
  | groupElements (gens : List Perm)

inductive Op
  | isCanonical (g : Group) | canonicalIndex (g : Group) | orbitSize (g : Group) | stabilizerOrder (g : Group)
  | fixedPoints (on : Gfp.Family)
  | projectiveAction (points : List Vec)

inductive Result
  | integers (xs : List Nat)
  | count (value size : Nat)
  | histogram (size : Nat) (bins : List Nat)
  | hits (size : Nat) (indices : List Nat) (members : List Mat)
  | perms (ps : List Perm)
  | invalid
  deriving DecidableEq, Repr

def reduceInt (red : Gfp.Red) (xs : List Nat) : Result :=
  match red with
  | .all => .integers xs
  | .histogram => .histogram xs.length (Gfp.histogramOf xs)
  | _ => .invalid

def reduceBool (red : Gfp.Red) (ms : List Mat) (flags : List Bool) : Result :=
  match red with
  | .all => .integers (flags.map fun b => if b then 1 else 0)
  | .count => .count (flags.filter id).length flags.length
  | .hits limit =>
    let idx := ((List.range flags.length).zip flags).filterMap fun (i, b) => if b then some i else none
    .hits flags.length idx ((idx.take limit).map fun i => ms.getD i [])
  | .histogram => .invalid

def orbitOp (g : Group) (f : Gfp.Family) (red : Gfp.Red) (value : List Nat → Nat) (bool : Bool) : Result :=
  if !actsOn g f then .invalid else
  let ms := f.members
  let orbits := (List.range ms.length).map fun i => orbit g f i
  if bool then reduceBool red ms (List.zipWith (fun o i => decide (leastOf o = i)) orbits (List.range ms.length))
  else reduceInt red (orbits.map value)

def run (op : Op) (f : Family) (red : Gfp.Red) : Result :=
  match op, f with
  | .isCanonical g, .gfp f => orbitOp g f red (fun _ => 0) true
  | .canonicalIndex g, .gfp f => orbitOp g f red leastOf false
  | .orbitSize g, .gfp f => orbitOp g f red (·.length) false
  | .stabilizerOrder g, .gfp f => orbitOp g f red (fun o => g.order / o.length) false
  | .fixedPoints on, .groupElements gens =>
    match on with
    | .subsets _ d on_k =>
      if !gens.all (·.length = d.length) then .invalid else
      let ks := subsetKeys d on_k
      reduceInt red ((permElements gens).map fun g => (ks.filter fun m => actPerm g m = m).length)
    | _ => .invalid
  | .projectiveAction pts, .gfp (.explicit p batch) =>
    match red with
    | .all => .perms (batch.map fun a => pts.map fun v => pts.idxOf (normalise p ((Gfp.matmul p [v] a).headD [])))
    | _ => .invalid
  | _, _ => .invalid

end Orbits
