import Lk.Reference

/-!
# automorphisms: executable reference

A finite group is one square Cayley table whose entries are labels `0..n-1`. An automorphism is a
permutation `f` of those labels with `f (a*b) = f(a)*f(b)`. The runtime validates the group laws
when it constructs a `group_tables` family.

`automorphisms` deliberately enumerates permutations by structural recursion. Oracle cases stay
small. The generic backend uses constraint propagation, but returns the same lexicographically
ordered set. `canonicalGenerators` scans that order and keeps an automorphism exactly when the
preceding choices do not generate it.
-/

namespace Automorphisms

open Lk

/-- Insert `x` at every position of a list. -/
def insertions (x : Nat) : List Nat → List (List Nat)
  | [] => [[x]]
  | y :: ys => (x :: y :: ys) :: (insertions x ys).map (y :: ·)

/-- Every permutation of a list, by structural recursion. -/
def permutations : List Nat → List (List Nat)
  | [] => [[]]
  | x :: xs => (permutations xs).flatMap (insertions x)

/-- Whether a label permutation preserves a Cayley table. -/
def preserves (table : Mat) (f : Perm) : Bool :=
  let n := table.length
  decide (f.length = n) && (List.range n).all fun a =>
    (List.range n).all fun b =>
      f.getD ((table.getD a []).getD b 0) 0 =
        (table.getD (f.getD a 0) []).getD (f.getD b 0) 0

/-- Every automorphism, lexicographic by its image list. -/
def automorphisms (table : Mat) : List Perm :=
  sortBy lexLe ((permutations (List.range table.length)).filter (preserves table))

/-- The subgroup generated by `gens`, lexicographic by image list. -/
def generated (n : Nat) (gens : List Perm) : List Perm :=
  sortBy lexLe (saturate (fun g => gens.map (compose g)) fuel [identityPerm n])

/-- The lexicographically greedy generating set of the full automorphism group. -/
def canonicalGenerators (table : Mat) : List Perm :=
  (automorphisms table).foldl (fun gens a =>
    if a ∈ generated table.length gens then gens else gens ++ [a]) []

/-- Number of elements commuting with every element. -/
def centerSize (table : Mat) : Nat :=
  let n := table.length
  ((List.range n).filter fun a =>
    (List.range n).all fun b =>
      (table.getD a []).getD b 0 = (table.getD b []).getD a 0).length

inductive Op
  | autOrder | autGenerators | holomorphOrder | innerAutIndex

inductive Value
  | generators (gens : List Perm)
  deriving DecidableEq, Repr

def run (op : Op) (f : Family) (red : Red) : Result Value :=
  match f with
  | .groupTables tables =>
    let autos := tables.map automorphisms
    match op with
    | .autOrder => reduceInt red tables (autos.map List.length)
    | .autGenerators => reduceValues red (tables.map fun table => .generators (canonicalGenerators table))
    | .holomorphOrder => reduceInt red tables (List.zipWith (fun table auts => table.length * auts.length) tables autos)
    | .innerAutIndex => reduceInt red tables (List.zipWith (fun table auts => auts.length * centerSize table / table.length) tables autos)
  | _ => .invalid

end Automorphisms
