import Mathlib
import Designs.Reference
import Orbits.Contract

/-!
# designs: contract

The executable reference uses lists for kernel evaluation. This file states its meaning with
Mathlib finite sets. The statements are obligations; the native backend is checked against the
reference, not proved correct here.
-/

namespace Designs.Contract

open Lk Designs

/-- A reference block interpreted as a finite subset of the labelled point set. -/
def toFinset (v : Nat) (block : Block) : Finset (Fin v) :=
  Finset.univ.filter fun x => x.val ∈ block

/-- A `t-(v,k,lambda)` design, with repeated indexed blocks retained by the list. -/
def IsDesign (v k t lambda : Nat) (blocks : List (Finset (Fin v))) : Prop :=
  (∀ block ∈ blocks, block.card = k) ∧
  ∀ points : Finset (Fin v), points.card = t →
    (blocks.filter fun block => points ⊆ block).length = lambda

/-- The parsed family has the same indexed blocks as the matrices in the runtime family. -/
def Represents (family : Family) (a : BlockFamily) : Prop :=
  parseFamily family = some a

/-- `lambdaVector` is indexed by all `t`-subsets in lexicographic order. -/
theorem lambdaVector_spec (a : BlockFamily) (t : Nat) (ht : t ≤ a.k) :
    let subsets := (combos (List.range a.v) t).map (toFinset a.v)
    (lambdaVector a t).length = subsets.length ∧
    ∀ i, i < subsets.length →
      (lambdaVector a t).getD i 0 =
        ((a.blocks.map (toFinset a.v)).filter fun block => subsets.getD i ∅ ⊆ block).length := by
  sorry

/-- The first output entry of `is_design` is true exactly for a finite `t`-design. -/
theorem isDesign_spec (a : BlockFamily) (t : Nat) (ht : t ≤ a.k) :
    ((isDesignData a t).getD 0 []).getD 0 0 = 1 ↔
      IsDesign a.v a.k t (((isDesignData a t).getD 0 []).getD 1 0)
        (a.blocks.map (toFinset a.v)) := by
  sorry

/-- Each intersection bin counts exactly the unordered indexed block pairs with that size. -/
theorem intersectionNumbers_spec (a : BlockFamily) (j : Nat) (hj : j ≤ a.k) :
    (intersectionNumbers a).getD j 0 =
      ((combos (List.range a.blocks.length) 2).filter fun pair =>
        let left := toFinset a.v (a.blocks.getD (pair.getD 0 0) [])
        let right := toFinset a.v (a.blocks.getD (pair.getD 1 0) [])
        (left ∩ right).card = j).length := by
  sorry

/-- A parallel class partitions every point exactly once. -/
def IsParallelClass (a : BlockFamily) (indices : List Nat) : Prop :=
  indices.Nodup ∧ (∀ i ∈ indices, i < a.blocks.length) ∧
  ∀ point : Fin a.v,
    (indices.filter fun i => point ∈ toFinset a.v (a.blocks.getD i [])).length = 1

def IsResolution (a : BlockFamily) (classes : Mat) : Prop :=
  (∀ parallelClass ∈ classes,
    IsParallelClass a parallelClass ∧ strictlyIncreasing parallelClass = true) ∧
  classes.flatten.Perm (List.range a.blocks.length) ∧
  strictlyIncreasing (classes.map (·.headD 0)) = true

/-- A nonempty `resolution` result is a resolution. Among resolutions with sorted classes and
increasing least block indices, its row-major list is lexicographically least. -/
theorem resolution_spec (a : BlockFamily) (witness : Mat) (h : resolution a = witness) :
    witness ≠ [] → IsResolution a witness ∧
      ∀ other, IsResolution a other → lexLe witness.flatten other.flatten = true := by
  sorry

/-- The dual test is the ordinary 2-design condition on blocks indexed by original points. Its
second entry is the multiplicity of the lexicographically first pair of dual points. -/
theorem dualIsDesign_spec (a : BlockFamily) :
    let dualBlocks : List (Finset (Fin a.blocks.length)) := List.ofFn fun point : Fin a.v =>
      Finset.univ.filter fun block : Fin a.blocks.length => point.val ∈ a.blocks.getD block.val []
    (((dualDesignData a).getD 0 []).getD 0 0 = 1 ↔
      ∃ k lambda, 2 ≤ k ∧ IsDesign a.blocks.length k 2 lambda dualBlocks) ∧
    ((dualDesignData a).getD 0 []).getD 1 0 =
      ((toFinset a.v (a.blocks.getD 0 [])) ∩ (toFinset a.v (a.blocks.getD 1 []))).card := by
  sorry

/-- The subgroup generated by `gens`, transported through its action on the lexicographically
ordered subsets. -/
noncomputable def subsetActionGroup (v s : Nat) (gens : List Perm) :
    Subgroup (Equiv.Perm (Fin (combos (List.range v) s).length)) := by
  sorry

/-- The reference orbit is exactly the Mathlib orbit under the generated subset-action group. -/
theorem subsetOrbit_mathlib (v s : Nat) (gens : List Perm) (x : Block)
    (hx : x ∈ combos (List.range v) s) (hg : gens.all fun g => g.length = v) :
    ∀ y, y ∈ subsetOrbit gens x ↔
      ∃ hi : (combos (List.range v) s).idxOf x < (combos (List.range v) s).length,
      ∃ hj : (combos (List.range v) s).idxOf y < (combos (List.range v) s).length,
        (⟨(combos (List.range v) s).idxOf y, hj⟩ : Fin _) ∈
          MulAction.orbit (subsetActionGroup v s gens)
            (⟨(combos (List.range v) s).idxOf x, hi⟩ : Fin _) := by
  sorry

/-- The Kramer-Mesner entries count containment from the canonical least representative of each
`t`-subset orbit into each `k`-subset orbit. -/
theorem kramerMesner_spec (v k t : Nat) (gens : List Perm) (ht : t ≤ k) (hk : k ≤ v) :
    let rows := subsetOrbits gens ((combos (List.range v) t).length + 1) (combos (List.range v) t)
    let cols := subsetOrbits gens ((combos (List.range v) k).length + 1) (combos (List.range v) k)
    kramerMesner v k t gens = rows.map fun rowOrbit =>
      cols.map fun colOrbit => (colOrbit.filter (contains (rowOrbit.headD []))).length := by
  sorry

end Designs.Contract
