import Mathlib
import Perm_groups.Reference

/-!
# perm_groups contract

These statements relate the executable list algorithms to Mathlib permutation groups. They are
obligations, not claims that the native backend has been proved correct. Tests compare native
answers with `Reference.lean`; the `sorry`s below record the remaining bridge from that reference
to Mathlib.
-/

namespace Perm_groups.Contract

open Lk

/-- A valid image list as a Mathlib permutation. -/
noncomputable def toPerm (n : Nat) (g : Perm) : Equiv.Perm (Fin n) := by
  classical
  sorry

/-- The subgroup generated by a list of permutation image lists. -/
noncomputable def generatedGroup (n : Nat) (gens : List Perm) : Subgroup (Equiv.Perm (Fin n)) :=
  Subgroup.closure (Set.range fun i : Fin gens.length => toPerm n (gens.getD i []))


def Fixes {n : Nat} (points : List Nat) (g : Equiv.Perm (Fin n)) : Prop :=
  ∀ b ∈ points, ∀ hb : b < n, g ⟨b, hb⟩ = ⟨b, hb⟩

/-- The pointwise stabilizer of a listed prefix inside a subgroup. -/
noncomputable def pointwiseStabilizer {n : Nat} (G : Subgroup (Equiv.Perm (Fin n)))
    (points : List Nat) : Subgroup (Equiv.Perm (Fin n)) := by
  classical
  sorry

/-- The subgroup generated by listed strong generators that fix a base prefix. -/
noncomputable def strongAt (n : Nat) (strong : List Perm) (points : List Nat) :
    Subgroup (Equiv.Perm (Fin n)) :=
  Subgroup.closure {g | (∃ i : Fin strong.length, g = toPerm n (strong.getD i [])) ∧ Fixes points g}


variable {n : Nat} {gens : List Perm}

theorem order_spec (h : validGroup n gens = true) :
    groupOrder n gens = Nat.card (generatedGroup n gens) := by
  sorry

theorem contains_spec {g : Perm} (h : validGroup n gens = true) (hg : isPerm n g = true) :
    contains n gens g = true ↔ toPerm n g ∈ generatedGroup n gens := by
  sorry

theorem transitive_spec (h : validGroup n gens = true) :
    isTransitive n gens = true ↔
      ∀ i j : Fin n, ∃ g ∈ generatedGroup n gens, g i = j := by
  sorry

theorem primitive_spec (h : validGroup n gens = true) :
    isPrimitive n gens = true ↔
      MulAction.IsPreprimitive (generatedGroup n gens) (Fin n) := by
  sorry

/-- Equal labels mean equal point orbits, and every label is the least point in its orbit. -/
theorem orbitPartition_spec (h : validGroup n gens = true) :
    let labels := orbitPartition n gens
    labels.length = n ∧
    (∀ i j (hi : i < n) (hj : j < n),
      (labels.getD i i = labels.getD j j ↔
        ∃ g ∈ generatedGroup n gens, g ⟨i, hi⟩ = ⟨j, hj⟩)) ∧
    (∀ i, i < n → labels.getD i i ≤ i) := by
  sorry

/-- The returned base has trivial pointwise stabilizer. The returned strong generators generate
G, and those fixing each base prefix generate the corresponding pointwise stabilizer. -/
theorem baseAndStrongGenerators_spec (h : validGroup n gens = true) :
    let (base, strong) := baseAndStrongGenerators n gens
    base.Nodup ∧ (∀ b ∈ base, b < n) ∧
    (∀ g ∈ generatedGroup n gens, Fixes base g → g = 1) ∧
    generatedGroup n strong = generatedGroup n gens ∧
    ∀ i, i ≤ base.length →
      strongAt n strong (base.take i) =
      pointwiseStabilizer (generatedGroup n gens) (base.take i) := by
  sorry

end Perm_groups.Contract
