import Lk.Reference

/-!
# perm_groups executable reference

Each family member is a list of permutation generators, one image list per row. `subsets` over
an `orbits.perms` dictionary therefore enumerates the subgroups generated by every k-subset of
the dictionary. Selecting the whole dictionary gives a singleton family for an explicitly given
group.

The small-oracle operations close the group by structural recursion. The BSGS value follows the
same deterministic Schreier construction as the native backend: generators are sorted, orbit
transversals use breadth-first order, and each stabilizer is generated by Schreier's lemma.
-/

namespace Perm_groups

open Lk


def canonPerms (gens : List Perm) : List Perm :=
  (sortBy lexLe (gens.filter fun g => g ≠ identityPerm g.length)).eraseDups

def canonNats (xs : List Nat) : List Nat := (sortBy (· ≤ ·) xs).eraseDups

def isPerm (n : Nat) (g : Perm) : Bool := g.length = n ∧ canonNats g = List.range n

def validGroup (n : Nat) (gens : List Perm) : Bool :=
  !gens.isEmpty ∧ gens.all (isPerm n)

/-- The degree and the generator rows of every group member, when the family has the required
permutation encoding. -/
def familyGenerators : Family → Option (Nat × List (List Perm))
  | f@(.subsets p d _) =>
    let n := (d.headD []).length
    if p = 0 ∧ !d.isEmpty ∧ d.all (isPerm n) then some (n, f.members) else none
  | f@(.explicit p batch) =>
    let n := ((batch.headD []).headD []).length
    if p = 0 ∧ !batch.isEmpty ∧ batch.all (validGroup n) then some (n, f.members) else none
  | _ => none


def pointOrbit (elements : List Perm) (i : Nat) : List Nat :=
  canonNats (elements.map fun g => g.getD i i)

def orbitPartition (n : Nat) (gens : List Perm) : List Nat :=
  let elements := permElements gens
  (List.range n).map fun i => (pointOrbit elements i).foldl min i

def isTransitive (n : Nat) (gens : List Perm) : Bool :=
  (pointOrbit (permElements gens) 0).length = n

def intersects (a b : List Nat) : Bool := a.any (· ∈ b)

def isBlock (elements : List Perm) (b : List Nat) : Bool :=
  elements.all fun g =>
    let image := canonNats (b.map fun i => g.getD i i)
    image = b ∨ !intersects image b

/-- Brute-force primitivity for the Lean oracle: inspect every subset containing point zero and
accept only singleton and whole-set blocks. -/
def isPrimitive (n : Nat) (gens : List Perm) : Bool :=
  let elements := permElements gens
  isTransitive n gens ∧
    (List.range (n + 1)).all fun k =>
      (combos (List.range n) k).all fun b =>
        if 0 ∈ b ∧ isBlock elements b then b.length = 1 ∨ b.length = n else true


/-! ## Deterministic Schreier chain -/

def inversePerm (g : Perm) : Perm := (List.range g.length).map fun i => g.idxOf i

def firstMoved (n : Nat) (gens : List Perm) : Option Nat :=
  (List.range n).find? fun i => gens.any fun g => g.getD i i ≠ i

/-- Add the images of one queued orbit point. -/
def addOrbitImages (gens : List Perm) (x : Nat × Perm) (reps : List (Nat × Perm)) : List (Nat × Perm) :=
  gens.foldl (fun out s =>
    let y := s.getD x.1 x.1
    if (out.map Prod.fst).contains y then out else out ++ [(y, compose x.2 s)]) reps

/-- Breadth-first Schreier transversal. `fuel = n` suffices because each step consumes one of at
most n queued points. -/
def orbitRepsAux (gens : List Perm) : Nat → Nat → List (Nat × Perm) → List (Nat × Perm)
  | 0, _, reps => reps
  | fuel + 1, front, reps =>
    if front < reps.length then
      let x := reps.getD front (0, [])
      orbitRepsAux gens fuel (front + 1) (addOrbitImages gens x reps)
    else reps

def orbitReps (n b : Nat) (gens : List Perm) : List (Nat × Perm) :=
  orbitRepsAux gens n 0 [(b, identityPerm n)]

def repAt (n y : Nat) (reps : List (Nat × Perm)) : Perm :=
  match reps.find? fun x => x.1 = y with
  | some x => x.2
  | none => identityPerm n

/-- Schreier generators `u_x s u_(x^s)⁻¹` for the next point stabilizer. -/
def nextGenerators (n : Nat) (gens : List Perm) (reps : List (Nat × Perm)) : List Perm :=
  let id := identityPerm n
  canonPerms (reps.flatMap fun x => gens.filterMap fun s =>
    let y := s.getD x.1 x.1
    let t := compose (compose x.2 s) (inversePerm (repAt n y reps))
    if t = id then none else some t)

structure Level where
  base : Nat
  gens : List Perm
  reps : List (Nat × Perm)
  deriving DecidableEq, Repr

def schreierChain : Nat → Nat → List Perm → List Level
  | 0, _, _ => []
  | fuel + 1, n, input =>
    let gens := canonPerms input
    match firstMoved n gens with
    | none => []
    | some b =>
      let reps := orbitReps n b gens
      { base := b, gens := gens, reps := reps } ::
        schreierChain fuel n (nextGenerators n gens reps)


def chainFor (n : Nat) (gens : List Perm) : List Level := schreierChain n n gens

def groupOrder (n : Nat) (gens : List Perm) : Nat :=
  (chainFor n gens).foldl (fun acc level => acc * level.reps.length) 1

def strongGenerators (levels : List Level) : List Perm :=
  canonPerms (levels.flatMap Level.gens)

def baseAndStrongGenerators (n : Nat) (gens : List Perm) : List Nat × List Perm :=
  let levels := chainFor n gens
  (levels.map Level.base, strongGenerators levels)

def sift : List Level → Perm → Option Perm
  | [], g => some g
  | level :: levels, g =>
    let image := g.getD level.base level.base
    match level.reps.find? fun x => x.1 = image with
    | none => none
    | some rep => sift levels (compose g (inversePerm rep.2))

def contains (n : Nat) (gens : List Perm) (g : Perm) : Bool :=
  match sift (chainFor n gens) g with
  | some residue => residue = identityPerm n
  | none => false


/-! ## Operations and values -/

inductive Op
  | order
  | contains (target : List Perm)
  | isTransitive
  | isPrimitive
  | orbitPartition
  | baseAndStrongGenerators

inductive Value
  | partition (labels : List Nat)
  | bsgs (data : List Nat × List Perm)
  deriving DecidableEq, Repr


def run (op : Op) (f : Family) (red : Red) : Result Value :=
  match familyGenerators f with
  | none => .invalid
  | some (n, groups) =>
    let members := f.members
    match op with
    | .order => reduceInt red members (groups.map (groupOrder n))
    | .contains targets =>
      match targets with
      | [target] =>
        if !isPerm n target then .invalid
        else reduceBool red members (groups.map fun gens => contains n gens target)
      | _ => .invalid
    | .isTransitive => reduceBool red members (groups.map (isTransitive n))
    | .isPrimitive => reduceBool red members (groups.map (isPrimitive n))
    | .orbitPartition =>
      reduceValues red (groups.map fun gens => .partition (orbitPartition n gens))
    | .baseAndStrongGenerators =>
      reduceValues red (groups.map fun gens => .bsgs (baseAndStrongGenerators n gens))

end Perm_groups
