#pragma once
#include "family.hpp"
#include "object.hpp"

#include <functional>
#include <string>
#include <vector>

namespace lk {

struct Request {
    std::shared_ptr<const Family> family;
    std::string module, op, reduction;
    std::map<std::string, std::shared_ptr<Object>> handle_args;
    std::map<std::string, uint64_t> int_args;
    uint32_t threads = 1;
    std::string value_type; /* from the manifest: integer, boolean, gfp.matrix, ... */
};

struct Backend {
    std::string module, name;
    std::function<bool()> available;
    std::function<bool(const Request &)> accepts;
    std::function<Result<std::shared_ptr<Object>>(const Request &)> run;
    int specificity; /* the runtime picks the accepting backend with the highest value */
    /* Family sizes and member indices are 128-bit. A backend that keeps them in 64-bit
     * variables must leave this false: the runtime then refuses families of 2^64 members or
     * more on its behalf, rather than let the narrowing silently corrupt indices. */
    bool big_families = false;
};

void register_backend(Backend b);
const std::vector<Backend> &backends();

/* Registration helper: a static instance in each backend source registers it at load time. */
struct BackendRegistration {
    explicit BackendRegistration(Backend b) { register_backend(std::move(b)); }
};

/* Manifest data generated by tools/manifest.py. */
struct ManifestOperation {
    const char *module, *name, *value;
    const char *const *args;
    const char *const *families; /* family kinds the operation is defined on; empty = any */
};
struct ManifestReduction {
    const char *name;
    const char *const *accepts;
    const char *const *args;
};
struct ManifestBackend {
    const char *module, *name;
    const char *const *features;
};
const std::vector<ManifestOperation> &manifest_operations();
const std::vector<ManifestReduction> &manifest_reductions();
const std::vector<ManifestBackend> &manifest_backends();
const char *manifest_describe_json();

bool cpu_has(const char *feature);

} // namespace lk
