import Lk.Reference

/-!
# small_groups: executable reference

A group arrives as a square multiplication table whose entries are labels `0..n-1`; the runtime
has already checked the group laws when it built the `groupTables` family, and the labelling is
the table's own, so the reference finds the identity rather than assuming it is label zero.

A subgroup is the increasing list of its labels. `derivedSeries` gives the finite chain
`G, [G,G], ...` up to its first stable term. Everything recurses structurally, on a fuel
argument where a fixpoint is what ends the recursion, so Lean's kernel can evaluate this file as
the test oracle.
-/

namespace Small_groups

open Lk

abbrev SubgroupLabels := List Nat

def mul (table : Mat) (a b : Nat) : Nat := (table.getD a []).getD b 0

def isIdentity (table : Mat) (e : Nat) : Bool :=
  (List.range table.length).all fun x => mul table e x = x && mul table x e = x

def identity (table : Mat) : Nat :=
  ((List.range table.length).find? (isIdentity table)).getD 0

def inverse (table : Mat) (x : Nat) : Nat :=
  let e := identity table
  (((List.range table.length).find? fun y => mul table x y = e && mul table y x = e)).getD 0

def elements (table : Mat) : SubgroupLabels := List.range table.length

/-- The subgroup generated by `gens`: close the identity under right multiplication. -/
def generated (table : Mat) (gens : List Nat) : SubgroupLabels :=
  sortBy (· ≤ ·) (saturate (fun x => gens.map (mul table x)) fuel [identity table])

def commutator (table : Mat) (x y : Nat) : Nat :=
  mul table (mul table (mul table (inverse table x) (inverse table y)) x) y

def commutatorSubgroup (table : Mat) (left right : SubgroupLabels) : SubgroupLabels :=
  generated table (left.flatMap fun x => right.map fun y => commutator table x y)

/-! ## Element orders and the exponent -/

def powerFrom (table : Mat) (x : Nat) : Nat → Nat
  | 0 => identity table
  | k + 1 => mul table (powerFrom table x k) x

def elementOrder (table : Mat) (x : Nat) : Nat :=
  ((((List.range table.length).map (· + 1)).find? fun k =>
    powerFrom table x k = identity table)).getD table.length

def lcm (a b : Nat) : Nat := if a = 0 || b = 0 then 0 else a / Nat.gcd a b * b

def exponent (table : Mat) : Nat :=
  (elements table).foldl (fun e x => lcm e (elementOrder table x)) 1

/-! ## Centre and conjugacy -/

def centre (table : Mat) : SubgroupLabels :=
  (elements table).filter fun x =>
    (elements table).all fun y => mul table x y = mul table y x

def conjugate (table : Mat) (g x : Nat) : Nat :=
  mul table (mul table (inverse table g) x) g

/-- The number of conjugacy classes, counted by their least member. -/
def classCount (table : Mat) : Nat :=
  ((elements table).filter fun x =>
    x = (elements table).foldl (fun least g => min least (conjugate table g x)) x).length

/-! ## Derived and lower central series -/

def derivedFrom (table : Mat) : Nat → SubgroupLabels → List SubgroupLabels
  | 0, h => [h]
  | fuel + 1, h =>
      let next := commutatorSubgroup table h h
      if next = h then [h] else h :: derivedFrom table fuel next

def derivedSeries (table : Mat) : List SubgroupLabels :=
  derivedFrom table table.length (elements table)

def derivedLength (table : Mat) : Nat := (derivedSeries table).length - 1

def lastTerm (series : List SubgroupLabels) : SubgroupLabels := series.getLast?.getD []

def isSolvable (table : Mat) : Bool := (lastTerm (derivedSeries table)).length = 1

def lowerCentralFrom (table : Mat) (whole : SubgroupLabels) : Nat → SubgroupLabels → Bool
  | 0, h => h.length = 1
  | fuel + 1, h =>
      if h.length = 1 then true
      else
        let next := commutatorSubgroup table h whole
        if next = h then false else lowerCentralFrom table whole fuel next

def isNilpotent (table : Mat) : Bool :=
  let whole := elements table
  lowerCentralFrom table whole table.length whole

/-! ## Subgroups

Every subgroup is generated by finitely many elements, so growing the subgroups found so far by
one element at a time reaches all of them. -/

def subgroups (table : Mat) : List SubgroupLabels :=
  saturate (fun h => (elements table).filterMap fun x =>
      if x ∈ h then none else some (generated table (x :: h)))
    fuel [[identity table]]

def isNormal (table : Mat) (h : SubgroupLabels) : Bool :=
  (elements table).all fun g => h.all fun x => conjugate table g x ∈ h

def subgroupCount (table : Mat) : Nat := (subgroups table).length

def normalSubgroupCount (table : Mat) : Nat :=
  ((subgroups table).filter (isNormal table)).length

/-! ## The operations -/

inductive Op
  | order | exponent | centre | centreOrder | classCount | derivedSeries | derivedLength
  | isNilpotent | isSolvable | subgroupCount | normalSubgroupCount

inductive Value
  | subgroup (labels : SubgroupLabels)
  | series (terms : List SubgroupLabels)
  deriving DecidableEq, Repr

def run (op : Op) (family : Family) (red : Red) : Result Value :=
  match family with
  | .groupTables tables =>
      match op with
      | .order => reduceInt red tables (tables.map (·.length))
      | .exponent => reduceInt red tables (tables.map Small_groups.exponent)
      | .centre => reduceValues red (tables.map fun t => .subgroup (Small_groups.centre t))
      | .centreOrder => reduceInt red tables (tables.map fun t => (Small_groups.centre t).length)
      | .classCount => reduceInt red tables (tables.map Small_groups.classCount)
      | .derivedSeries => reduceValues red (tables.map fun t => .series (Small_groups.derivedSeries t))
      | .derivedLength => reduceInt red tables (tables.map Small_groups.derivedLength)
      | .isNilpotent => reduceBool red tables (tables.map Small_groups.isNilpotent)
      | .isSolvable => reduceBool red tables (tables.map Small_groups.isSolvable)
      | .subgroupCount => reduceInt red tables (tables.map Small_groups.subgroupCount)
      | .normalSubgroupCount => reduceInt red tables (tables.map Small_groups.normalSubgroupCount)
  | _ => .invalid

end Small_groups
