/* small_groups generic backend: portable C++.
 *
 * A group is a multiplication table plus bit sets over its labels: a subgroup is one mask of
 * 64-bit words, closure under multiplication is a queue over set bits, and the subgroups are
 * found by growing the ones already known by a single element at a time. Two elements of the
 * same coset Hx grow H to the same subgroup, so one representative per coset does the work of
 * the coset. Input groups are independent, so they split across threads. */
#include "../../../../runtime/src/reduce.hpp"

#include <bit>
#include <numeric>
#include <unordered_set>

namespace lk::small_groups {
namespace {

using R = Result<std::shared_ptr<Object>>;
constexpr int INVALID = 1;

/* A set of element labels: word w holds the labels 64w .. 64w + 63. */
using Mask = std::vector<uint64_t>;

struct MaskHash {
    size_t operator()(const Mask &mask) const {
        size_t hash = 0xcbf29ce484222325ull;
        for (uint64_t word : mask) hash = (hash ^ word) * 0x100000001b3ull;
        return hash;
    }
};

struct Table {
    uint64_t n = 0;
    uint64_t words = 0;
    std::vector<Entry> product;
    Entry identity = 0;
    std::vector<Entry> inverse;

    Entry mul(Entry a, Entry b) const { return product[(uint64_t)a * n + b]; }

    Entry commutator(Entry x, Entry y) const {
        return mul(mul(mul(inverse[x], inverse[y]), x), y);
    }

    Mask empty_set() const { return Mask(words, 0); }

    Mask whole() const {
        Mask out = empty_set();
        for (uint64_t x = 0; x < n; ++x) add(out, (Entry)x);
        return out;
    }

    static bool has(const Mask &mask, Entry x) { return (mask[x >> 6] >> (x & 63)) & 1; }
    static void add(Mask &mask, Entry x) { mask[x >> 6] |= uint64_t{1} << (x & 63); }

    static uint64_t size(const Mask &mask) {
        uint64_t count = 0;
        for (uint64_t word : mask) count += (uint64_t)std::popcount(word);
        return count;
    }

    template <class F>
    void each(const Mask &mask, F visit) const {
        for (uint64_t w = 0; w < words; ++w)
            for (uint64_t bits = mask[w]; bits; bits &= bits - 1)
                visit((Entry)(w * 64 + (uint64_t)std::countr_zero(bits)));
    }

    std::vector<uint8_t> flags(const Mask &mask) const {
        std::vector<uint8_t> out(n, 0);
        each(mask, [&](Entry x) { out[x] = 1; });
        return out;
    }

    /* The subgroup generated by `generators`, which the queue reaches by right multiplication. */
    Mask generated(const std::vector<Entry> &generators) const {
        Mask seen = empty_set();
        std::vector<Entry> queue{identity};
        add(seen, identity);
        for (size_t front = 0; front < queue.size(); ++front) {
            Entry x = queue[front];
            for (Entry generator : generators) {
                Entry y = mul(x, generator);
                if (!has(seen, y)) {
                    add(seen, y);
                    queue.push_back(y);
                }
            }
        }
        return seen;
    }

    /* [L, R]: the subgroup generated by the commutators, of which at most n are distinct. */
    Mask commutator_subgroup(const Mask &left, const Mask &right) const {
        Mask values = empty_set();
        each(left, [&](Entry x) { each(right, [&](Entry y) { add(values, commutator(x, y)); }); });
        std::vector<Entry> generators;
        each(values, [&](Entry x) { generators.push_back(x); });
        return generated(generators);
    }

    uint64_t element_order(Entry x) const {
        Entry value = identity;
        for (uint64_t k = 1; k <= n; ++k) {
            value = mul(value, x);
            if (value == identity) return k;
        }
        return 0;
    }

    uint64_t exponent() const {
        uint64_t result = 1;
        for (uint64_t x = 0; x < n; ++x) result = std::lcm(result, element_order((Entry)x));
        return result;
    }

    Mask centre() const {
        Mask out = empty_set();
        for (uint64_t x = 0; x < n; ++x) {
            bool central = true;
            for (uint64_t y = 0; y < n && central; ++y)
                central = mul((Entry)x, (Entry)y) == mul((Entry)y, (Entry)x);
            if (central) add(out, (Entry)x);
        }
        return out;
    }

    uint64_t centre_order() const { return size(centre()); }

    /* G, [G,G], ... through the first term that repeats. */
    std::vector<Mask> derived_series() const {
        Mask current = whole();
        std::vector<Mask> out;
        for (uint64_t step = 0; step <= n; ++step) {
            out.push_back(current);
            auto next = commutator_subgroup(current, current);
            if (next == current) return out;
            current = std::move(next);
        }
        return out;
    }

    bool is_solvable() const { return size(derived_series().back()) == 1; }

    bool is_nilpotent() const {
        const Mask all = whole();
        Mask current = all;
        for (uint64_t step = 0; step <= n; ++step) {
            if (size(current) == 1) return true;
            auto next = commutator_subgroup(current, all);
            if (next == current) return false;
            current = std::move(next);
        }
        return false;
    }

    uint64_t class_count() const {
        std::vector<uint8_t> seen(n, 0);
        uint64_t count = 0;
        for (uint64_t x = 0; x < n; ++x) {
            if (seen[x]) continue;
            ++count;
            for (uint64_t g = 0; g < n; ++g) seen[mul(mul(inverse[g], (Entry)x), (Entry)g)] = 1;
        }
        return count;
    }

    /* Every subgroup. A subgroup other than the trivial one is generated by a maximal proper
     * subgroup of itself and any element outside it, so adjoining one element to the subgroups
     * already found reaches all of them, and carrying the generators along keeps each closure
     * to |K| products per generator. Elements of one coset Hx give the same subgroup, so each
     * coset is grown once. */
    std::vector<Mask> subgroups() const {
        struct Grown {
            Mask mask;
            std::vector<Entry> generators;
        };
        Mask trivial = empty_set();
        add(trivial, identity);
        std::vector<Grown> found{{trivial, {}}};
        std::unordered_set<Mask, MaskHash> seen{trivial};
        for (size_t front = 0; front < found.size(); ++front) {
            const Mask subgroup = found[front].mask;
            Mask covered = subgroup;
            for (uint64_t x = 0; x < n; ++x) {
                if (has(covered, (Entry)x)) continue;
                each(subgroup, [&](Entry h) { add(covered, mul(h, (Entry)x)); });
                auto generators = found[front].generators;
                generators.push_back((Entry)x);
                auto grown = generated(generators);
                if (seen.insert(grown).second) found.push_back({std::move(grown), std::move(generators)});
            }
        }
        std::vector<Mask> out;
        out.reserve(found.size());
        for (auto &one : found) out.push_back(std::move(one.mask));
        return out;
    }

    bool is_normal(const Mask &subgroup) const {
        bool normal = true;
        each(subgroup, [&](Entry x) {
            for (uint64_t g = 0; g < n; ++g)
                if (!has(subgroup, mul(mul(inverse[g], x), (Entry)g))) normal = false;
        });
        return normal;
    }

    uint64_t normal_subgroup_count() const {
        uint64_t count = 0;
        for (const auto &subgroup : subgroups()) count += is_normal(subgroup);
        return count;
    }
};

Result<Table> analyse(const Entry *entries, uint64_t n) {
    using T = Result<Table>;
    Table table;
    table.n = n;
    table.words = (n + 63) / 64;
    table.product.assign(entries, entries + n * n);

    bool found_identity = false;
    for (uint64_t e = 0; e < n && !found_identity; ++e) {
        found_identity = true;
        for (uint64_t x = 0; x < n; ++x)
            if (table.mul((Entry)e, (Entry)x) != x || table.mul((Entry)x, (Entry)e) != x) {
                found_identity = false;
                break;
            }
        if (found_identity) table.identity = (Entry)e;
    }
    if (!found_identity) return T::failure(4, "group_tables family lost its identity invariant");

    table.inverse.assign(n, 0);
    for (uint64_t x = 0; x < n; ++x) {
        bool found = false;
        for (uint64_t y = 0; y < n; ++y)
            if (table.mul((Entry)x, (Entry)y) == table.identity) {
                table.inverse[x] = (Entry)y;
                found = true;
                break;
            }
        if (!found) return T::failure(4, "group_tables family lost its inverse invariant");
    }
    return T::success(std::move(table));
}

Result<std::vector<Table>> tables(const Request &req) {
    using T = Result<std::vector<Table>>;
    const Matrix &batch = *req.family->data;
    std::vector<Table> out;
    out.reserve(batch.count);
    for (uint64_t i = 0; i < batch.count; ++i) {
        auto table = analyse(batch.at(i), batch.rows);
        if (!table.ok)
            return T::failure(table.error.status, "member " + std::to_string(i) + ": " + table.error.message);
        out.push_back(std::move(table.value));
    }
    return T::success(std::move(out));
}

template <class Value>
R reduce_scalar(const Request &req, const std::vector<Table> &groups, bool boolean, Value value) {
    Reduction reduction = parse_reduction(req.reduction);
    Shared shared;
    auto prepared = prepare_all(reduction, groups.size(), shared);
    if (!prepared.ok) return R::failure(prepared.error.status, prepared.error.message);
    uint32_t threads = std::max<uint32_t>(1, std::min<uint64_t>(req.threads, groups.empty() ? 1 : groups.size()));
    std::vector<Accumulator> accumulators;
    for (uint32_t thread = 0; thread < threads; ++thread) accumulators.emplace_back(reduction, &shared);
    auto statuses = parallel_ranges(groups.size(), threads,
        [&](uint32_t thread, uint64_t begin, uint64_t end) -> Status {
            for (uint64_t i = begin; i < end; ++i) {
                if (accumulators[thread].exhausted(i)) break;
                uint64_t answer = value(groups[i]);
                if (boolean) accumulators[thread].boolean(i, answer != 0);
                else accumulators[thread].integer(i, answer);
            }
            return ok();
        });
    for (const auto &status : statuses)
        if (!status.ok) return R::failure(status.error.status, status.error.message);
    return assemble(req, reduction, accumulators, shared);
}

R run_centre(const Request &req, const std::vector<Table> &groups) {
    if (req.reduction != "all") return R::failure(INVALID, "centre only accepts the all reduction");
    auto result = std::make_shared<Subgroups>();
    result->count = groups.size();
    result->degree = req.family->rows();
    result->entries.resize(result->count * result->degree);
    for (uint64_t i = 0; i < groups.size(); ++i) {
        auto subgroup = groups[i].flags(groups[i].centre());
        std::copy(subgroup.begin(), subgroup.end(), result->entries.begin() + i * result->degree);
    }
    auto object = std::make_shared<Object>();
    object->kind = "small_groups.subgroups";
    object->subgroups = std::move(result);
    return R::success(object);
}

R run_derived_series(const Request &req, const std::vector<Table> &groups) {
    if (req.reduction != "all") return R::failure(INVALID, "derived_series only accepts the all reduction");
    std::vector<std::vector<Mask>> series(groups.size());
    uint32_t threads = std::max<uint32_t>(1, std::min<uint64_t>(req.threads, groups.empty() ? 1 : groups.size()));
    auto statuses = parallel_ranges(groups.size(), threads, [&](uint32_t, uint64_t begin, uint64_t end) -> Status {
        for (uint64_t i = begin; i < end; ++i) series[i] = groups[i].derived_series();
        return ok();
    });
    for (const auto &status : statuses)
        if (!status.ok) return R::failure(status.error.status, status.error.message);

    auto result = std::make_shared<GroupSeries>();
    result->count = groups.size();
    result->degree = req.family->rows();
    result->offsets.push_back(0);
    for (const auto &one : series) result->offsets.push_back(result->offsets.back() + one.size());
    result->entries.reserve(result->offsets.back() * result->degree);
    for (uint64_t i = 0; i < series.size(); ++i)
        for (const auto &term : series[i]) {
            auto membership = groups[i].flags(term);
            result->entries.insert(result->entries.end(), membership.begin(), membership.end());
        }
    auto object = std::make_shared<Object>();
    object->kind = "small_groups.series";
    object->group_series = std::move(result);
    return R::success(object);
}

R run(const Request &req) {
    if (req.family->kind != Family::Kind::GroupTables)
        return R::failure(INVALID, "small_groups operations need a group_tables family");
    auto input = tables(req);
    if (!input.ok) return R::failure(input.error.status, input.error.message);
    const auto &groups = input.value;
    if (req.op == "order") return reduce_scalar(req, groups, false, [](const Table &g) { return g.n; });
    if (req.op == "exponent") return reduce_scalar(req, groups, false, [](const Table &g) { return g.exponent(); });
    if (req.op == "centre_order") return reduce_scalar(req, groups, false, [](const Table &g) { return g.centre_order(); });
    if (req.op == "class_count") return reduce_scalar(req, groups, false, [](const Table &g) { return g.class_count(); });
    if (req.op == "derived_length")
        return reduce_scalar(req, groups, false, [](const Table &g) { return g.derived_series().size() - 1; });
    if (req.op == "is_nilpotent") return reduce_scalar(req, groups, true, [](const Table &g) { return (uint64_t)g.is_nilpotent(); });
    if (req.op == "is_solvable") return reduce_scalar(req, groups, true, [](const Table &g) { return (uint64_t)g.is_solvable(); });
    if (req.op == "subgroup_count")
        return reduce_scalar(req, groups, false, [](const Table &g) { return (uint64_t)g.subgroups().size(); });
    if (req.op == "normal_subgroup_count")
        return reduce_scalar(req, groups, false, [](const Table &g) { return g.normal_subgroup_count(); });
    if (req.op == "centre") return run_centre(req, groups);
    if (req.op == "derived_series") return run_derived_series(req, groups);
    return R::failure(4, "unknown small_groups operation " + req.op);
}

BackendRegistration registration{Backend{
    "small_groups", "generic",
    [] { return true; },
    [](const Request &req) { return req.family->kind == Family::Kind::GroupTables; },
    run,
    0}};

} // namespace
} // namespace lk::small_groups
