"""The direct small_groups implementation, the benchmark baseline.

Every answer is computed from the multiplication table the obvious way: element orders by
repeated multiplication, the centre by testing every pair, series by taking commutators until
nothing changes, and the subgroups by closing every set of elements found so far under one more
element. The generic backend does the same mathematics on bit sets and across threads.
"""
from __future__ import annotations

import itertools
import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT / "python"))
from lemmakernel import naive as rt  # noqa: E402
from lemmakernel.interchange import Family, GroupSeries, NATURALS, Subgroups  # noqa: E402


def identity(table):
    n = len(table)
    for e in range(n):
        if all(table[e][x] == x == table[x][e] for x in range(n)):
            return e
    raise ValueError("multiplication table has no two-sided identity")


def inverses(table, e):
    n = len(table)
    out = []
    for x in range(n):
        y = next((y for y in range(n) if table[x][y] == e == table[y][x]), None)
        if y is None:
            raise ValueError("multiplication table has an element without a two-sided inverse")
        out.append(y)
    return out


def element_order(table, e, x):
    value, k = e, 0
    while True:
        value, k = table[value][x], k + 1
        if value == e:
            return k


def exponent(table, e):
    return math.lcm(*(element_order(table, e, x) for x in range(len(table))))


def centre(table):
    n = len(table)
    return [x for x in range(n) if all(table[x][y] == table[y][x] for y in range(n))]


def generated(table, e, generators):
    """The subgroup generated by `generators`, as a sorted list of labels."""
    seen = {e}
    queue = [e]
    for x in queue:
        for g in generators:
            y = table[x][g]
            if y not in seen:
                seen.add(y)
                queue.append(y)
    return sorted(seen)


def commutator_subgroup(table, e, inv, left, right):
    return generated(table, e, [table[table[table[inv[x]][inv[y]]][x]][y] for x in left for y in right])


def derived_series(table, e, inv):
    current = list(range(len(table)))
    out = []
    for _ in range(len(table) + 1):
        out.append(current)
        following = commutator_subgroup(table, e, inv, current, current)
        if following == current:
            return out
        current = following
    raise AssertionError("derived series of a finite group did not stabilise")


def is_nilpotent(table, e, inv):
    whole = list(range(len(table)))
    current = whole
    for _ in range(len(table) + 1):
        if len(current) == 1:
            return True
        following = commutator_subgroup(table, e, inv, current, whole)
        if following == current:
            return False
        current = following
    raise AssertionError("lower central series of a finite group did not stabilise")


def class_count(table, inv):
    unseen = set(range(len(table)))
    count = 0
    while unseen:
        x = min(unseen)
        unseen.difference_update(table[table[inv[g]][x]][g] for g in range(len(table)))
        count += 1
    return count


def subgroups(table, e):
    """Every subgroup, grown from the ones already found by adjoining one element."""
    found = [[e]]
    seen = {(e,)}
    for subgroup in found:
        for x in range(len(table)):
            if x in subgroup:
                continue
            grown = generated(table, e, subgroup + [x])
            if tuple(grown) not in seen:
                seen.add(tuple(grown))
                found.append(grown)
    return found


def is_normal(table, inv, subgroup):
    present = set(subgroup)
    return all(table[table[inv[g]][x]][g] in present
               for g in range(len(table)) for x in subgroup)


def membership(labels, n):
    present = set(labels)
    return [int(x in present) for x in range(n)]


def run(op: str, family: Family, reduction: str = "all", prefix: int | None = None, **args):
    op = op.removeprefix("small_groups.")
    if family.kind != "group_tables":
        raise ValueError("small_groups operations need a group_tables family")
    tables = list(itertools.islice(rt.iter_members(family), prefix))
    n = family.children[0].rows
    checked = [(table, identity(table)) for table in tables]

    if op == "centre":
        entries = [flag for table, _ in checked for flag in membership(centre(table), n)]
        return rt.reduce_values(reduction, Subgroups(len(checked), n, entries))
    if op == "derived_series":
        offsets, entries = [0], []
        for table, e in checked:
            series = derived_series(table, e, inverses(table, e))
            offsets.append(offsets[-1] + len(series))
            entries.extend(flag for term in series for flag in membership(term, n))
        return rt.reduce_values(reduction, GroupSeries(len(checked), n, offsets, entries))

    if op == "order":
        values = [len(table) for table, _ in checked]
    elif op == "exponent":
        values = [exponent(table, e) for table, e in checked]
    elif op == "centre_order":
        values = [len(centre(table)) for table, _ in checked]
    elif op == "class_count":
        values = [class_count(table, inverses(table, e)) for table, e in checked]
    elif op == "derived_length":
        values = [len(derived_series(table, e, inverses(table, e))) - 1 for table, e in checked]
    elif op == "subgroup_count":
        values = [len(subgroups(table, e)) for table, e in checked]
    elif op == "normal_subgroup_count":
        values = [sum(is_normal(table, inverses(table, e), h) for h in subgroups(table, e))
                  for table, e in checked]
    elif op == "is_solvable":
        flags = [len(derived_series(table, e, inverses(table, e))[-1]) == 1 for table, e in checked]
        return rt.reduce_bool(reduction, flags, tables, NATURALS, **args)
    elif op == "is_nilpotent":
        flags = [is_nilpotent(table, e, inverses(table, e)) for table, e in checked]
        return rt.reduce_bool(reduction, flags, tables, NATURALS, **args)
    else:
        raise ValueError(f"unknown operation {op}")
    return rt.reduce_int(reduction, values, tables, NATURALS)
