# Generated by tools/manifest.py from runtime/manifest.toml and modules/*/manifest.toml. Do not edit.
RUNTIME = {'reductions': [{'accepts': ['*'],
                 'name': 'all',
                 'summary': 'Materialise the per-member value for every member, in family order. Integers '
                            'and booleans come back as kind `integers`.'},
                {'accepts': ['boolean'],
                 'name': 'count',
                 'summary': 'Number of members whose value is true (kind `count`: value, visited, '
                            'family_size).'},
                {'accepts': ['integer'],
                 'name': 'histogram',
                 'summary': 'Number of members per value (kind `histogram`: u64 bins[0..max]).'},
                {'accepts': ['boolean'],
                 'args': ['limit'],
                 'name': 'hits',
                 'summary': 'Canonical indices of every member whose value is true, and the first `limit` of '
                            'them materialised (kind `hits`).'}]}
MODULES = [{'backends': [{'accepts': 'any p < 2^32; any family; any operation',
                'name': 'generic',
                'sources': ['backends/generic/gfp_generic.cpp'],
                'summary': 'Portable C++: depth-first enumeration with an incremental echelon basis shared '
                           'along each prefix, subtree pruning, threads over top-level branches.'}],
  'families': [{'member': 'gfp.matrix',
                'name': 'explicit',
                'summary': 'One member per matrix of the batch, in batch order.'},
               {'member': 'gfp.matrix',
                'name': 'subsets',
                'summary': 'Every k-row matrix formed by choosing k rows of the dictionary, indices '
                           'increasing; lexicographic order of the index tuple.'},
               {'member': 'gfp.matrix',
                'name': 'grassmannian',
                'summary': 'Every h-dimensional subspace of F_p^n as its reduced row echelon basis (h x n); '
                           'ordered by pivot set (lexicographic), then by free entries (row-major, '
                           'lexicographic).'},
               {'member': 'gfp.matrix',
                'name': 'all_matrices',
                'summary': 'Every rows x cols matrix over F_p; index is the row-major base-p number of the '
                           'entries.'},
               {'member': 'gfp.matrix',
                'name': 'transform',
                'summary': 'Each member M of the inner family replaced by M * C for a fixed matrix C. Same '
                           'order and indices.'},
               {'member': 'gfp.matrix',
                'name': 'stack',
                'summary': 'Each member M of the inner family with a fixed block of rows appended below it. '
                           'Same order and indices.'}],
  'kinds': [{'name': 'gfp.matrix',
             'params': ['p', 'count', 'rows', 'cols'],
             'payload': 'count*rows*cols entries',
             'summary': 'A batch of `count` matrices, each rows x cols over F_p. Vectors are 1 x n '
                        'matrices.'},
            {'name': 'gfp.basis',
             'params': ['p', 'count', 'cols'],
             'payload': 'u64 offsets[count+1], then entries of offsets[count] row vectors of length cols',
             'summary': 'For each of `count` members, a list of row vectors (ragged).'},
            {'name': 'gfp.solutions',
             'params': ['p', 'count', 'length'],
             'payload': 'u8 solvable[count], then count*length entries',
             'summary': 'Per member: a flag and a solution vector (zeros when unsolvable).'},
            {'name': 'gfp.inverses',
             'params': ['p', 'count', 'n'],
             'payload': 'u8 invertible[count], then count*n*n entries',
             'summary': 'Per member: a flag and the inverse (zeros when singular).'},
            {'name': 'gfp.witness',
             'params': ['p', 'count', 'rows', 'cols'],
             'payload': 'count*rows*cols entries of R, then count*rows*rows entries of T',
             'summary': 'Per member A: its rref R and an invertible T with T*A = R.'}],
  'module': {'bench': 'bench/bench.py',
             'contract': 'lean/Gfp/Contract.lean',
             'lean': 'lean',
             'naive': 'naive/naive.py',
             'name': 'gfp',
             'reference': 'lean/Gfp/Reference.lean',
             'summary': 'Linear algebra over F_p (p prime) on families of matrices: rref, rank, nullspace, '
                        'solve, inverse, span membership.',
             'tests': 'tests/test_gfp.py',
             'version': 1},
  'operations': [{'name': 'rank', 'summary': 'Rank of the member.', 'value': 'integer'},
                 {'name': 'nullity', 'summary': 'cols - rank.', 'value': 'integer'},
                 {'name': 'full_row_rank', 'summary': 'rank == rows.', 'value': 'boolean'},
                 {'name': 'full_col_rank', 'summary': 'rank == cols.', 'value': 'boolean'},
                 {'args': ['target'],
                  'name': 'in_span',
                  'summary': 'The 1 x cols matrix `target` lies in the row space of the member.',
                  'value': 'boolean'},
                 {'name': 'rref',
                  'summary': 'Reduced row echelon form of the member.',
                  'value': 'gfp.matrix'},
                 {'name': 'nullspace',
                  'summary': 'Canonical basis of {x : M x^T = 0}: one vector per free column f of rref(M), '
                             'in increasing f, with x_f = 1, x_pivot_i = -R[i][f], zeros elsewhere.',
                  'value': 'gfp.basis'},
                 {'args': ['rhs'],
                  'families': ['explicit'],
                  'name': 'solve',
                  'summary': 'For member A_i and rhs vector b_i (1 x rows): x with A_i x^T = b_i^T, free '
                             'coordinates zero; flag 0 when none exists.',
                  'value': 'gfp.solutions'},
                 {'families': ['explicit'],
                  'name': 'inverse',
                  'summary': 'Inverse of a square member; flag 0 when singular.',
                  'value': 'gfp.inverses'},
                 {'families': ['explicit'],
                  'name': 'rref_witness',
                  'summary': 'rref R and the transform T of Gauss-Jordan elimination with first-nonzero-row '
                             'pivoting, so T*A = R with T invertible.',
                  'value': 'gfp.witness'}]},
 {'backends': [{'accepts': 'any group given by generators; orbits computed by breadth-first search per '
                           'member; group order by closure up to 2^26 elements',
                'name': 'generic',
                'sources': ['backends/generic/orbits_generic.cpp'],
                'summary': 'Portable C++: per-member orbit BFS over the generators with index ranking '
                           "through the family's unrank/rank, threaded over members; fixed_points on subsets "
                           'by cycle type (coefficient of x^k in the product of 1 + x^len over cycles). No '
                           'orderly-generation pruning yet.'}],
  'families': [{'member': 'orbits.perms',
                'name': 'group_elements',
                'summary': 'Every element of the permutation group generated by the given orbits.perms, as a '
                           '1 x n permutation, in lexicographic order of the image list. Size is the group '
                           'order.'}],
  'kinds': [{'name': 'orbits.perms',
             'params': ['n', 'count'],
             'payload': 'count*n u32 point indices; element g maps point i to entry g*n+i',
             'summary': 'A batch of `count` permutations of {0..n-1}. As a group argument, the generators.'}],
  'module': {'bench': 'bench/bench.py',
             'contract': 'lean/Orbits/Contract.lean',
             'lean': 'lean',
             'naive': 'naive/naive.py',
             'name': 'orbits',
             'reference': 'lean/Orbits/Reference.lean',
             'summary': 'Finite permutation and matrix groups acting on families: canonical representatives, '
                        'orbit sizes, stabilisers, fixed points (Burnside), induced point actions.',
             'tests': 'tests/test_orbits.py',
             'version': 1},
  'operations': [{'args': ['group'],
                  'families': ['subsets', 'grassmannian', 'all_matrices'],
                  'name': 'is_canonical',
                  'summary': 'The member has the least index in its orbit under `group`. With `hits`, the '
                             'orbit transversal; with `count`, the number of orbits.',
                  'value': 'boolean'},
                 {'args': ['group'],
                  'families': ['subsets', 'grassmannian', 'all_matrices'],
                  'name': 'canonical_index',
                  'summary': "The least index in the member's orbit under `group`.",
                  'value': 'integer'},
                 {'args': ['group'],
                  'families': ['subsets', 'grassmannian', 'all_matrices'],
                  'name': 'orbit_size',
                  'summary': 'Number of members in the orbit of the member under `group`.',
                  'value': 'integer'},
                 {'args': ['group'],
                  'families': ['subsets', 'grassmannian', 'all_matrices'],
                  'name': 'stabilizer_order',
                  'summary': 'Order of the stabiliser of the member in `group`, i.e. |group| / orbit_size. '
                             'Needs the group order, so `group` must generate a group the backend can '
                             'enumerate.',
                  'value': 'integer'},
                 {'args': ['on'],
                  'families': ['group_elements'],
                  'name': 'fixed_points',
                  'summary': 'For each group element, the number of members of the family `on` it fixes. Sum '
                             'over the group divided by the group order is the number of orbits (Burnside), '
                             'an independent check of is_canonical/count.',
                  'value': 'integer'},
                 {'args': ['points'],
                  'families': ['explicit'],
                  'name': 'projective_action',
                  'summary': 'For each n x n matrix A of the batch, the permutation of the projective points '
                             '`points` (a dictionary of 1 x n rows, each scaled so its first nonzero entry '
                             'is 1, pairwise distinct) induced by v -> normalise(v A). Fails if the '
                             'dictionary is not closed under some A. Bridges matrix groups to `subsets` '
                             'families over projective points.',
                  'value': 'orbits.perms'}]}]
