# Generated by tools/manifest.py from runtime/manifest.toml and modules/*/manifest.toml. Do not edit.
RUNTIME = {'families': [{'lean': 'explicit',
               'member': 'matrix',
               'name': 'explicit',
               'summary': 'One member per matrix or permutation of the batch, in batch order.'},
              {'lean': 'subsets',
               'member': 'matrix',
               'name': 'subsets',
               'summary': 'Every k-row matrix formed by choosing k rows of a matrix or permutation '
                          'dictionary, indices increasing; lexicographic order of the index tuple.'},
              {'lean': 'grassmannian',
               'member': 'gfp.matrix',
               'name': 'grassmannian',
               'summary': 'Every h-dimensional subspace of a field with q labelled elements as its reduced '
                          'row echelon basis (h x n); ordered by pivot set (lexicographic), then by free '
                          'entries (row-major, lexicographic). The consuming module supplies extension-field '
                          'arithmetic.'},
              {'lean': 'allMatrices',
               'member': 'gfp.matrix',
               'name': 'all_matrices',
               'summary': 'Every rows x cols matrix with entries 0..q-1; index is the row-major base-q '
                          'number of the entries.'},
              {'lean': 'transform',
               'member': 'gfp.matrix',
               'name': 'transform',
               'summary': 'Each prime-field member M replaced by M * C for a fixed matrix C. Same order and '
                          'indices.'},
              {'lean': 'stack',
               'member': 'gfp.matrix',
               'name': 'stack',
               'summary': 'Each member M of the inner family with a fixed block of rows appended below it. '
                          'Same order and indices.'},
              {'lean': 'groupElements',
               'member': 'orbits.perms',
               'name': 'group_elements',
               'summary': 'Every element of the permutation group generated by the given orbits.perms, as a '
                          '1 x n permutation, in lexicographic order of the image list. Size is the group '
                          'order.'},
              {'lean': 'groupTables',
               'member': 'lk.naturals',
               'name': 'group_tables',
               'summary': 'Finite groups as n x n Cayley tables with entries in 0..n-1, in stored order. A '
                          'table batch gives explicit groups or a complete stored catalogue; permutation '
                          'generators are converted to one table with lexicographically ordered elements.'},
              {'lean': 'subsetsOf',
               'member': 'gfp.matrix',
               'name': 'subsets_of',
               'summary': 'Every k-subset of the members of an inner family, each member flattened to one '
                          'row of rows*cols entries, indices increasing; lexicographic order of the index '
                          'tuple. The inner family is materialised once and must have at most 2^22 members.'},
              {'lean': 'symmetricMatrices',
               'member': 'gfp.matrix',
               'name': 'symmetric_matrices',
               'summary': 'Every symmetric n x n matrix with entries 0..q-1; index is the base-q number of '
                          'the upper triangle read row-major.'},
              {'lean': 'range',
               'member': 'lk.naturals',
               'name': 'range',
               'summary': 'The integers a <= x < b as 1 x 1 natural-number matrices; index is x - a.'},
              {'lean': 'words',
               'member': 'lk.naturals',
               'name': 'words',
               'summary': 'Every word of the given length over the alphabet 0..alphabet-1 as a 1 x length '
                          'natural-number matrix; index is the base-alphabet number of the word.'},
              {'lean': 'partitions',
               'member': 'lk.naturals',
               'name': 'partitions',
               'summary': 'Partitions of total with optional largest-part, part-count and multiplicity '
                          'bounds, and optional distinct or odd parts; one decreasing row padded to total '
                          'entries with zeros, in descending lexicographic order. A zero bound is '
                          'unrestricted.'},
              {'lean': 'compositions',
               'member': 'lk.naturals',
               'name': 'compositions',
               'summary': 'Positive compositions of total with optional exact length and largest-part bound; '
                          'one row padded to total entries with zeros. Lengths increase first, then rows are '
                          'descending lexicographic. A zero bound or length is unrestricted.'},
              {'lean': 'standardTableaux',
               'member': 'lk.naturals',
               'name': 'standard_tableaux',
               'summary': 'Every standard Young tableau of a fixed positive partition shape, padded with '
                          'zeros to its bounding rectangle. Order recursively places the largest entry in '
                          'removable corners from the top row down.'}],
 'kinds': [{'lean': 'naturals',
            'name': 'lk.naturals',
            'params': ['count', 'rows', 'cols'],
            'payload': 'count*rows*cols u32 natural numbers',
            'summary': 'A batch of natural-number matrices with entries below 2^32.'}],
 'reductions': [{'accepts': ['*'],
                 'name': 'all',
                 'summary': 'Materialise the per-member value for every member, in family order. Integers '
                            'and booleans come back as kind `integers`.'},
                {'accepts': ['boolean'],
                 'name': 'count',
                 'summary': 'Number of members whose value is true (kind `count`: value, visited, '
                            'family_size).'},
                {'accepts': ['integer'],
                 'name': 'histogram',
                 'summary': 'Number of members per value (kind `histogram`: u64 bins[0..max]).'},
                {'accepts': ['boolean'],
                 'args': {'limit': 'int'},
                 'name': 'hits',
                 'summary': 'Canonical indices of every member whose value is true, and the first `limit` of '
                            'them materialised (kind `hits`).'},
                {'accepts': ['boolean'],
                 'name': 'first',
                 'summary': 'The least canonical index whose value is true, materialised, or found = 0 when '
                            'there is none (kind `first`). Stops as soon as nothing below the best hit '
                            'remains; `visited` is index + 1 when found and family_size otherwise.'},
                {'accepts': ['integer'],
                 'name': 'sum',
                 'summary': 'Sum of the values over the family (kind `count`: value, visited, family_size); '
                            'fails if it exceeds 2^64 - 1.'},
                {'accepts': ['integer'],
                 'name': 'max',
                 'summary': 'The largest value and the least index attaining it, materialised (kind '
                            '`extremum`).'},
                {'accepts': ['integer'],
                 'name': 'min',
                 'summary': 'The smallest value and the least index attaining it, materialised (kind '
                            '`extremum`).'}]}
MODULES = [{'backends': [{'accepts': 'every group_tables family whose answers fit in u64',
                'name': 'generic',
                'sources': ['backends/generic/automorphisms_generic.cpp'],
                'summary': 'Portable C++: enumerate table automorphisms by backtracking partial bijections, '
                           'close each assignment under multiplication, and split independent input groups '
                           'across threads.'}],
  'kinds': [{'lean': 'generators',
             'name': 'automorphisms.generators',
             'params': ['count', 'order'],
             'payload': 'u64 offsets[count+1], then offsets[count]*order u32 images',
             'summary': 'For each input group of order n, a ragged list of permutations of 0..n-1. The list '
                        'is the lexicographically greedy generating set of Aut(G): scan every automorphism '
                        'in lexicographic order and keep it exactly when the preceding choices do not '
                        'generate it.'}],
  'module': {'cases': 'cases.py',
             'contract': 'lean/Automorphisms/Contract.lean',
             'lean': 'lean',
             'naive': 'naive/naive.py',
             'name': 'automorphisms',
             'reference': 'lean/Automorphisms/Reference.lean',
             'summary': 'Automorphism groups of finite groups: order, canonical generators, holomorph order, '
                        'and the index of the inner automorphism group.',
             'version': 1},
  'operations': [{'families': ['group_tables'],
                  'name': 'aut_order',
                  'summary': 'The order of the automorphism group Aut(G).',
                  'value': 'integer'},
                 {'families': ['group_tables'],
                  'name': 'aut_generators',
                  'summary': 'Canonical generators of Aut(G), acting on Cayley-table labels. Scan all '
                             'automorphisms lexicographically and keep one exactly when it is outside the '
                             'subgroup generated by earlier choices.',
                  'value': 'automorphisms.generators'},
                 {'families': ['group_tables'],
                  'name': 'holomorph_order',
                  'summary': 'The order |Hol(G)| = |G| * |Aut(G)|.',
                  'value': 'integer'},
                 {'families': ['group_tables'],
                  'name': 'inner_aut_index',
                  'summary': 'The index [Aut(G) : Inn(G)] = |Out(G)|, computed as |Aut(G)| * |Z(G)| / |G|.',
                  'value': 'integer'}],
  'rejections': [{'case': 'matrix is not a group family', 'error': 'group_tables'}]},
 {'backends': [{'accepts': 'permutation groups on subsets, subsets_of, and words; group closure up to 2^26 '
                           'elements',
                'name': 'generic',
                'sources': ['backends/generic/burnside_generic.cpp'],
                'summary': 'Portable C++: closes the generator group, groups elements by cycle-count vector, '
                           "uses subset generating functions and Polya's q^cycles formula, and never "
                           'enumerates the acted-on family.'}],
  'kinds': [{'lean': 'count',
             'name': 'burnside.counts',
             'params': ['count'],
             'payload': 'count u64 values',
             'summary': 'A batch of unsigned counts. orbit_count and fixed_count each return a batch of '
                        'one.'},
            {'lean': 'cycleIndexTerm',
             'name': 'burnside.cycle_index',
             'params': ['degree', 'count', 'denominator'],
             'payload': 'For each of count terms: u64 multiplicity, then degree u64 cycle counts '
                        'c_1,...,c_degree',
             'summary': 'The cycle index (1/denominator) sum multiplicity*product_i x_i^c_i. Terms are '
                        'sorted lexicographically by (c_1,...,c_degree), and zero coefficients are '
                        'omitted.'}],
  'module': {'cases': 'cases.py',
             'contract': 'lean/Burnside/Contract.lean',
             'lean': 'lean',
             'naive': 'naive/naive.py',
             'name': 'burnside',
             'reference': 'lean/Burnside/Reference.lean',
             'summary': 'Burnside and Polya orbit counts for permutation groups on subsets and words, '
                        'computed from cycle types without enumerating the acted-on family.',
             'version': 1},
  'operations': [{'args': {'group': 'group'},
                  'families': ['subsets', 'subsets_of', 'words'],
                  'name': 'orbit_count',
                  'summary': 'Number of orbits of the family under a permutation group. Subsets use '
                             'dictionary positions; words use coordinate positions. Returns one count and '
                             'never enumerates family members.',
                  'value': 'burnside.counts'},
                 {'args': {'group': 'group'},
                  'families': ['subsets', 'subsets_of', 'words'],
                  'name': 'cycle_index',
                  'summary': "Cycle index of the permutation group on the family's positions. One canonical "
                             'sparse term is returned for each distinct cycle-count vector.',
                  'value': 'burnside.cycle_index'},
                 {'args': {'g': 'perms'},
                  'families': ['subsets', 'subsets_of', 'words'],
                  'name': 'fixed_count',
                  'summary': 'Number of family members fixed by the single permutation g. Returns one count '
                             'without enumerating family members.',
                  'value': 'burnside.counts'}],
  'rejections': [{'case': 'permutations on a range', 'error': 'families only'},
                 {'case': 'C4 on length-five words', 'error': 'positions'},
                 {'case': 'matrix group on words', 'error': 'permutation'},
                 {'case': 'two permutations passed as g', 'error': 'single permutation'}]},
 {'backends': [{'accepts': 'finite groups given by permutation generators; graph invariants use adjacency '
                           'matrices; is_ci_set exhausts inverse pairs and group automorphisms',
                'name': 'generic',
                'sources': ['backends/generic/cayley_generic.cpp'],
                'summary': 'Portable C++: group closure and multiplication table once per request, BFS '
                           'invariants, and exact graph canonical forms by equitable partition refinement '
                           'plus individualisation.'}],
  'module': {'cases': 'cases.py',
             'contract': 'lean/Cayley/Contract.lean',
             'lean': 'lean',
             'naive': 'naive/naive.py',
             'name': 'cayley',
             'reference': 'lean/Cayley/Reference.lean',
             'summary': 'Simple undirected Cayley graphs Cay(G,S). A member is a fixed-size list of distinct '
                        'nonidentity elements of the permutation group G. SimpleGraph.fromRel symmetrises S '
                        'when S is not inverse-closed. Girth and Mathlib-style diameter are 0 for acyclic '
                        'and disconnected graphs, respectively.',
             'version': 1},
  'operations': [{'args': {'group': 'group'},
                  'families': ['explicit', 'subsets', 'subsets_of'],
                  'name': 'connected',
                  'summary': 'Whether the simple undirected Cayley graph is connected. For '
                             'non-inverse-closed S, adjacency uses S union S^-1.',
                  'value': 'boolean'},
                 {'args': {'degree': 'int', 'group': 'group'},
                  'families': ['explicit', 'subsets', 'subsets_of'],
                  'name': 'is_regular_of_degree',
                  'summary': 'Whether every vertex has exactly `degree` neighbours in the simple undirected '
                             'Cayley graph.',
                  'value': 'boolean'},
                 {'args': {'group': 'group'},
                  'families': ['explicit', 'subsets', 'subsets_of'],
                  'name': 'girth',
                  'summary': 'Length of a shortest cycle, or 0 for an acyclic graph, matching Mathlib '
                             'SimpleGraph.girth.',
                  'value': 'integer'},
                 {'args': {'group': 'group'},
                  'families': ['explicit', 'subsets', 'subsets_of'],
                  'name': 'diameter',
                  'summary': 'Maximum shortest-path distance when connected, or 0 when disconnected, '
                             'matching Mathlib SimpleGraph.diam.',
                  'value': 'integer'},
                 {'args': {'group': 'group'},
                  'families': ['explicit', 'subsets', 'subsets_of'],
                  'name': 'aut_order',
                  'summary': 'Order of the full automorphism group of the unlabelled graph, counted by '
                             'equitable partition refinement and individualisation.',
                  'value': 'integer'},
                 {'args': {'group': 'group'},
                  'families': ['explicit', 'subsets', 'subsets_of'],
                  'name': 'is_ci_set',
                  'summary': 'Whether S is inverse-closed and every inverse-closed identity-free T of the '
                             'same size with Cay(G,T) isomorphic to Cay(G,S) is an Aut(G)-image of S. '
                             'Non-inverse-closed S returns false.',
                  'value': 'boolean'}],
  'rejections': [{'case': 'matrix group is unsupported', 'error': 'permutation group'},
                 {'case': 'identity is not a connection', 'error': 'identity'},
                 {'case': 'element outside G', 'error': 'not an element'},
                 {'case': 'range is not a connection family', 'error': 'families only'},
                 {'case': 'C4 singletons',
                  'error': 'does not accept integer',
                  'op': 'girth',
                  'reduction': 'count'}]},
 {'backends': [{'accepts': 'block families with canonical standard-basis block members; permutation groups '
                           'for Kramer-Mesner matrices',
                'name': 'generic',
                'sources': ['backends/generic/designs_generic.cpp'],
                'summary': 'Portable C++: one pass for incidence counts and intersections, canonical '
                           'exact-cover search for resolutions, and subset-orbit closure for Kramer-Mesner '
                           'matrices.'}],
  'kinds': [{'lean': 'matrix',
             'name': 'designs.matrix',
             'params': ['count', 'rows', 'cols'],
             'payload': 'count*rows*cols u64 entries, row-major, little-endian',
             'summary': 'A batch of fixed-shape natural-number matrices with 64-bit entries. Design '
                        'operations return one matrix.'}],
  'module': {'cases': 'cases.py',
             'contract': 'lean/Designs/Contract.lean',
             'lean': 'lean',
             'naive': 'naive/naive.py',
             'name': 'designs',
             'reference': 'lean/Designs/Reference.lean',
             'summary': 'Finite block designs represented by families of canonical point-subset matrices: '
                        't-design tests and lambda vectors, resolutions, dual 2-designs, block-intersection '
                        'distributions, and canonical Kramer-Mesner matrices.',
             'version': 1},
  'operations': [{'args': {'t': 'int'},
                  'name': 'is_design',
                  'summary': 'For the whole block family, return [[flag, lambda_0]], where flag says every '
                             't-subset occurs equally often and lambda_0 is the multiplicity of the '
                             'lexicographically first t-subset. Blocks are k x v matrices whose rows are '
                             'distinct standard basis vectors in increasing point order.',
                  'value': 'designs.matrix'},
                 {'args': {'t': 'int'},
                  'name': 'lambda_vector',
                  'summary': 'For the whole block family, return one row containing the multiplicity of '
                             'every t-subset of {0,...,v-1}, in lexicographic subset order.',
                  'value': 'designs.matrix'},
                 {'name': 'is_resolvable',
                  'summary': 'Return the lexicographically least resolution witness as a matrix of block '
                             'indices, one parallel class per row and indices increasing within each row; '
                             'return the unique empty 0 x 0 matrix when no resolution exists.',
                  'value': 'designs.matrix'},
                 {'name': 'dual_is_design',
                  'summary': 'Return [[flag, lambda_0]] for whether the dual incidence structure is a '
                             '2-design; lambda_0 is the intersection size of the first two indexed blocks.',
                  'value': 'designs.matrix'},
                 {'name': 'intersection_numbers',
                  'summary': 'Return one row h[0..k], where h[j] is the number of unordered pairs of '
                             'distinct indexed blocks with intersection size j.',
                  'value': 'designs.matrix'},
                 {'args': {'group': 'group', 't': 'int'},
                  'families': ['subsets'],
                  'name': 'kramer_mesner_matrix',
                  'summary': 'For a group on the dictionary positions of the k-subsets family, return the '
                             'Kramer-Mesner matrix. Rows and columns are t-subset and k-subset orbits '
                             'ordered by their least lexicographic member; entry (i,j) counts blocks in '
                             'column orbit j containing the least member of row orbit i.',
                  'value': 'designs.matrix'}],
  'rejections': [{'case': 'malformed repeated point', 'error': 'distinct standard basis'},
                 {'case': 'Kramer-Mesner with a matrix group', 'error': 'permutation'}]},
 {'backends': [{'accepts': 'subsets_of(group_elements(G), k) for permutation groups; forbidden subgroup '
                           'closure up to 2^26 elements',
                'name': 'generic',
                'sources': ['backends/generic/difference_sets_generic.cpp'],
                'summary': 'Portable C++: updates quotient multiplicities along the subsets depth-first walk '
                           'and rejects whole subtrees as soon as a target multiplicity is exceeded; threads '
                           'over top-level branches.'}],
  'module': {'cases': 'cases.py',
             'contract': 'lean/Difference_sets/Contract.lean',
             'lean': 'lean',
             'naive': 'naive/naive.py',
             'name': 'difference_sets',
             'reference': 'lean/Difference_sets/Reference.lean',
             'summary': 'Difference sets and regular partial and relative difference sets in finite '
                        'permutation groups. Differences are ordered right quotients x*y^-1. The difference '
                        'multiset is a 1 x |G| natural matrix, indexed by the lexicographic group_elements '
                        'order and including the k diagonal identity quotients.',
             'version': 1},
  'operations': [{'families': ['subsets_of'],
                  'name': 'is_difference_set',
                  'summary': 'Whether the member is a (v,k,lambda) difference set in G, with v=|G|, k '
                             'inferred from the family and lambda=k(k-1)/(v-1). Every nonidentity right '
                             'quotient x*y^-1 of distinct elements must occur lambda times.',
                  'value': 'boolean'},
                 {'families': ['subsets_of'],
                  'name': 'difference_multiset',
                  'summary': 'The multiplicities of all ordered right quotients x*y^-1, including x=y, as '
                             "one row indexed by group_elements(G)'s lexicographic order. This order is the "
                             'canonical answer.',
                  'value': 'lk.naturals'},
                 {'args': {'lambda': 'int', 'mu': 'int'},
                  'families': ['subsets_of'],
                  'name': 'is_pds',
                  'summary': 'Whether the member is a regular (v,k,lambda,mu) partial difference set: '
                             'identity-free, inverse-closed, and each nonidentity quotient has multiplicity '
                             'lambda inside D and mu outside D. v and k are inferred.',
                  'value': 'boolean'},
                 {'args': {'forbidden': 'perms'},
                  'families': ['subsets_of'],
                  'name': 'is_relative_difference_set',
                  'summary': 'Whether the member is a relative difference set in G relative to '
                             'N=<forbidden>. Nonidentity elements of N occur zero times and every element of '
                             'G\\N occurs lambda=k(k-1)/(|G|-|N|) times as an ordered right quotient.',
                  'value': 'boolean'}],
  'rejections': [{'case': 'plain subsets', 'error': 'defined on subsets_of'},
                 {'case': 'subsets of a range', 'error': 'needs subsets_of'},
                 {'case': 'foreign forbidden subgroup', 'error': 'subgroup of the ambient group'},
                 {'case': 'C4 differences',
                  'error': 'does not accept',
                  'op': 'difference_multiset',
                  'reduction': 'count'}]},
 {'backends': [{'accepts': 'any prime 3 < p < 2^32; any family of 1 x 2 members; any operation',
                'name': 'generic',
                'sources': ['backends/generic/elliptic_curves_fp_generic.cpp'],
                'summary': 'Portable C++: per request a table of square-root counts and of fourth and sixth '
                           'powers, shared by every member; per member a linear pass over x, and for '
                           'group_structure the point list with orders from the factorisation of the group '
                           'order.'}],
  'kinds': [{'lean': 'group',
             'name': 'elliptic_curves_fp.group',
             'params': ['count'],
             'payload': 'u64 pairs (n1, n2), one per member',
             'summary': 'Per member: the invariant factors (n1, n2) of E(F_p), n1 | n2 and n1*n2 = '
                        'point_count; (0, 0) for a singular member.'}],
  'module': {'cases': 'cases.py',
             'contract': 'lean/Elliptic_curves_fp/Contract.lean',
             'lean': 'lean',
             'naive': 'naive/naive.py',
             'name': 'elliptic_curves_fp',
             'reference': 'lean/Elliptic_curves_fp/Reference.lean',
             'summary': 'Curves y^2 = x^3 + a*x + b over F_p (p prime, p > 3) on families of 1 x 2 members '
                        '(a, b): point counts, singularity, supersingularity, j-invariants, F_p-isomorphism '
                        'classes and group structure. Canonical choices. A member is one row of two entries, '
                        'a = M[0][0] and b = M[0][1]; families whose members have another shape, and primes '
                        '2 and 3, are refused rather than reinterpreted. point_count is the number of '
                        'F_p-points of the projective cubic y^2*z = x^3 + a*x*z^2 + b*z^3, so it counts the '
                        'one point at infinity [0:1:0] and is defined for singular (a, b) as well. '
                        'j_invariant is 1728*4a^3/(4a^3+27b^2) in F_p, and p (a value outside F_p) when the '
                        'pair is singular. The isomorphism class of (a, b) is its orbit {(u^4*a, u^6*b) : u '
                        'in F_p^*}, which for a nonsingular pair is exactly the F_p-isomorphism class of the '
                        'curve; its canonical representative is the lexicographically least pair of the '
                        'orbit. group_structure is the pair (n1, n2) of invariant factors with n1 | n2 and '
                        'E(F_p) = Z/n1 x Z/n2, and (0, 0) for a singular pair.',
             'version': 1},
  'operations': [{'name': 'point_count',
                  'summary': 'Number of F_p-points of y^2*z = x^3 + a*x*z^2 + b*z^3, the affine solutions of '
                             'y^2 = x^3 + a*x + b plus the point at infinity.',
                  'value': 'integer'},
                 {'name': 'nonsingular',
                  'summary': 'Whether 4*a^3 + 27*b^2 is nonzero in F_p, equivalently the discriminant '
                             '-16*(4*a^3+27*b^2) is nonzero and (a, b) is an elliptic curve.',
                  'value': 'boolean'},
                 {'name': 'supersingular',
                  'summary': 'Whether the member is nonsingular and its point count is p + 1, equivalently '
                             'the trace of Frobenius vanishes (p > 3).',
                  'value': 'boolean'},
                 {'name': 'j_invariant',
                  'summary': '1728*4*a^3 / (4*a^3 + 27*b^2) in F_p, as a representative in 0..p-1; p for a '
                             'singular member, which has no j-invariant.',
                  'value': 'integer'},
                 {'name': 'is_canonical',
                  'summary': 'Whether (a, b) is the lexicographically least pair of its isomorphism class '
                             '{(u^4*a, u^6*b) : u in F_p^*}; counting these counts F_p-isomorphism classes '
                             'of curves.',
                  'value': 'boolean'},
                 {'name': 'class_size',
                  'summary': 'Number of distinct pairs in {(u^4*a, u^6*b) : u in F_p^*}, the size of the '
                             "member's isomorphism class inside the p^2 pairs.",
                  'value': 'integer'},
                 {'name': 'group_structure',
                  'summary': 'Invariant factors (n1, n2) of E(F_p) with n1 | n2 and n1*n2 = point_count; n2 '
                             'is the group exponent. (0, 0) for a singular member.',
                  'value': 'elliptic_curves_fp.group'}],
  'rejections': [{'case': 'F_3 pairs', 'error': 'prime p > 3', 'op': 'point_count'},
                 {'case': 'stacked pairs F_5', 'error': '1 x 2', 'op': 'point_count'},
                 {'case': 'plane points F_5', 'error': '1 x 2', 'op': 'j_invariant'},
                 {'case': 'reduction rejections F_7',
                  'error': 'does not accept integer',
                  'op': 'point_count',
                  'reduction': 'count'},
                 {'case': 'reduction rejections F_7',
                  'error': 'does not accept boolean',
                  'op': 'nonsingular',
                  'reduction': 'histogram'},
                 {'case': 'reduction rejections F_7',
                  'error': 'does not accept',
                  'op': 'group_structure',
                  'reduction': 'histogram'}]},
 {'backends': [{'accepts': 'any p < 2^32; any family; any operation',
                'name': 'generic',
                'sources': ['backends/generic/gfp_generic.cpp'],
                'summary': 'Portable C++: depth-first enumeration with an incremental echelon basis shared '
                           'along each prefix, subtree pruning, threads over top-level branches.'}],
  'kinds': [{'lean': 'matrix',
             'name': 'gfp.matrix',
             'params': ['p', 'count', 'rows', 'cols'],
             'payload': 'count*rows*cols entries',
             'summary': 'A batch of `count` labelled field matrices, each rows x cols. Vectors are 1 x n '
                        'matrices; the consuming module interprets the field-size tag.'},
            {'lean': 'basis',
             'name': 'gfp.basis',
             'params': ['p', 'count', 'cols'],
             'payload': 'u64 offsets[count+1], then entries of offsets[count] row vectors of length cols',
             'summary': 'For each of `count` labelled field matrices, a list of row vectors (ragged).'},
            {'lean': 'solution',
             'name': 'gfp.solutions',
             'params': ['p', 'count', 'length'],
             'payload': 'u8 solvable[count], then count*length entries',
             'summary': 'Per labelled field matrix: a flag and a solution vector (zeros when unsolvable).'},
            {'lean': 'inverse',
             'name': 'gfp.inverses',
             'params': ['p', 'count', 'n'],
             'payload': 'u8 invertible[count], then count*n*n entries',
             'summary': 'Per labelled field matrix: a flag and the inverse (zeros when singular).'},
            {'lean': 'witness',
             'name': 'gfp.witness',
             'params': ['p', 'count', 'rows', 'cols'],
             'payload': 'count*rows*cols entries of R, then count*rows*rows entries of T',
             'summary': 'Per member A: its rref R and an invertible T with T*A = R.'}],
  'module': {'cases': 'cases.py',
             'contract': 'lean/Gfp/Contract.lean',
             'lean': 'lean',
             'naive': 'naive/naive.py',
             'name': 'gfp',
             'reference': 'lean/Gfp/Reference.lean',
             'summary': 'Linear algebra over F_p (p prime) on families of matrices: rref, rank, nullspace, '
                        'solve, inverse, span membership.',
             'version': 1},
  'operations': [{'name': 'rank', 'summary': 'Rank of the member.', 'value': 'integer'},
                 {'name': 'nullity', 'summary': 'cols - rank.', 'value': 'integer'},
                 {'name': 'full_row_rank', 'summary': 'rank == rows.', 'value': 'boolean'},
                 {'name': 'full_col_rank', 'summary': 'rank == cols.', 'value': 'boolean'},
                 {'args': {'target': 'vector'},
                  'name': 'in_span',
                  'summary': 'The 1 x cols matrix `target` lies in the row space of the member.',
                  'value': 'boolean'},
                 {'name': 'rref',
                  'summary': 'Reduced row echelon form of the member.',
                  'value': 'gfp.matrix'},
                 {'name': 'nullspace',
                  'summary': 'Canonical basis of {x : M x^T = 0}: one vector per free column f of rref(M), '
                             'in increasing f, with x_f = 1, x_pivot_i = -R[i][f], zeros elsewhere.',
                  'value': 'gfp.basis'},
                 {'args': {'rhs': 'vectors'},
                  'families': ['explicit'],
                  'name': 'solve',
                  'summary': 'For member A_i and rhs vector b_i (1 x rows): x with A_i x^T = b_i^T, free '
                             'coordinates zero; flag 0 when none exists.',
                  'value': 'gfp.solutions'},
                 {'families': ['explicit'],
                  'name': 'inverse',
                  'summary': 'Inverse of a square member; flag 0 when singular.',
                  'value': 'gfp.inverses'},
                 {'families': ['explicit'],
                  'name': 'rref_witness',
                  'summary': 'rref R and the transform T of Gauss-Jordan elimination with first-nonzero-row '
                             'pivoting, so T*A = R with T invertible.',
                  'value': 'gfp.witness'}],
  'rejections': [{'case': 'grassmannian F_2',
                  'error': 'does not accept integer',
                  'op': 'rank',
                  'reduction': 'count'},
                 {'case': 'grassmannian F_2',
                  'error': 'does not accept',
                  'op': 'rref',
                  'reduction': 'histogram'},
                 {'case': 'grassmannian F_2',
                  'error': 'does not accept',
                  'op': 'nullspace',
                  'reduction': 'count'},
                 {'case': 'grassmannian F_2', 'error': 'explicit families only', 'op': 'inverse'},
                 {'case': 'grassmannian F_2', 'error': 'explicit families only', 'op': 'rref_witness'}]},
 {'backends': [{'accepts': 'q < 2^32 with an explicit monic irreducible modulus; every non-arithmetic matrix '
                           'family except transform; solve and inverse on explicit families',
                'name': 'generic',
                'sources': ['backends/generic/gfq_generic.cpp'],
                'summary': 'Portable C++ polynomial-basis arithmetic and depth-first family enumeration with '
                           'a shared incremental echelon basis.'}],
  'module': {'cases': 'cases.py',
             'contract': 'lean/Gfq/Contract.lean',
             'lean': 'lean',
             'naive': 'naive/naive.py',
             'name': 'gfq',
             'reference': 'lean/Gfq/Reference.lean',
             'summary': 'Linear algebra over GF(q), presented as F_p[x]/(modulus). Elements use base-p '
                        'little-endian coefficient codes 0..q-1. RREF takes the first nonzero row as pivot; '
                        'nullspace and solve set free coordinates to zero in increasing-column order.',
             'version': 1},
  'operations': [{'args': {'modulus': 'vector'},
                  'families': ['explicit',
                               'subsets',
                               'subsets_of',
                               'grassmannian',
                               'all_matrices',
                               'symmetric_matrices',
                               'stack'],
                  'name': 'rank',
                  'summary': 'Rank over F_p[x]/(modulus).',
                  'value': 'integer'},
                 {'args': {'modulus': 'vector', 'target': 'vector'},
                  'families': ['explicit',
                               'subsets',
                               'subsets_of',
                               'grassmannian',
                               'all_matrices',
                               'symmetric_matrices',
                               'stack'],
                  'name': 'in_span',
                  'summary': 'Whether target lies in the row space over F_p[x]/(modulus).',
                  'value': 'boolean'},
                 {'args': {'modulus': 'vector'},
                  'families': ['explicit',
                               'subsets',
                               'subsets_of',
                               'grassmannian',
                               'all_matrices',
                               'symmetric_matrices',
                               'stack'],
                  'name': 'rref',
                  'summary': 'Unique reduced row echelon form, with the first nonzero row at or below each '
                             'pivot chosen during elimination.',
                  'value': 'gfp.matrix'},
                 {'args': {'modulus': 'vector'},
                  'families': ['explicit',
                               'subsets',
                               'subsets_of',
                               'grassmannian',
                               'all_matrices',
                               'symmetric_matrices',
                               'stack'],
                  'name': 'nullspace',
                  'summary': 'Canonical basis of {x : M x^T = 0}: one vector per free column f in increasing '
                             'order, x_f = 1 and x_pivot_i = -R[i,f].',
                  'value': 'gfp.basis'},
                 {'args': {'modulus': 'vector', 'rhs': 'vectors'},
                  'families': ['explicit'],
                  'name': 'solve',
                  'summary': 'For A_i and b_i, the solution of A_i x^T = b_i^T with every free coordinate '
                             'zero; a false flag and zero vector when inconsistent.',
                  'value': 'gfp.solutions'},
                 {'args': {'modulus': 'vector'},
                  'families': ['explicit'],
                  'name': 'inverse',
                  'summary': 'The unique inverse of each square member; a false flag and zero matrix when '
                             'singular.',
                  'value': 'gfp.inverses'}],
  'rejections': [{'case': 'reducible modulus', 'error': 'irreducible'},
                 {'case': 'wrong field size', 'error': 'q must equal'},
                 {'case': 'transform over a prime field', 'error': 'defined on'},
                 {'case': 'nonsquare inverse', 'error': 'square'},
                 {'case': 'Grassmannian solve', 'error': 'explicit families only'}]},
 {'backends': [{'accepts': 'any F_2 matrix family; canonical_form enumerates row permutations and chooses '
                           'the best column order',
                'name': 'generic',
                'sources': ['backends/generic/hadamard_generic.cpp'],
                'summary': 'Portable C++: threaded member evaluation; sign dot products use bit equality, '
                           'and canonical forms enumerate row orders while sorting normalised columns.'}],
  'module': {'cases': 'cases.py',
             'contract': 'lean/Hadamard/Contract.lean',
             'lean': 'lean',
             'naive': 'naive/naive.py',
             'name': 'hadamard',
             'reference': 'lean/Hadamard/Reference.lean',
             'summary': 'Hadamard, skew, regular and conference tests for F_2 matrices read as signs (0 = '
                        '+1, 1 = -1), plus the lexicographically least form under signed row and column '
                        'permutations.',
             'version': 1},
  'operations': [{'name': 'is_hadamard',
                  'summary': 'Whether the member is square and its sign lift H satisfies H H^T = n I.',
                  'value': 'boolean'},
                 {'name': 'is_skew',
                  'summary': 'Whether the member is square and its sign lift H satisfies H + H^T = 2 I. This '
                             'tests skew type and does not also require the Hadamard property.',
                  'value': 'boolean'},
                 {'name': 'is_regular',
                  'summary': 'Whether the member is square and every row sum and every column sum of its '
                             'sign lift are one common integer.',
                  'value': 'boolean'},
                 {'name': 'is_conference',
                  'summary': 'Whether n >= 2, every diagonal bit is 0, and replacing that +1 diagonal by '
                             'zero gives C C^T = (n-1) I. Requiring diagonal bits 0 makes the encoding '
                             'unique.',
                  'value': 'boolean'},
                 {'name': 'canonical_form',
                  'summary': 'The row-major lexicographically least F_2 matrix obtainable by permuting and '
                             'independently negating rows and columns. Bits use 0 = +1 and 1 = -1.',
                  'value': 'gfp.matrix'}],
  'rejections': [{'case': 'ternary sign input', 'error': 'no available backend accepts', 'op': 'is_hadamard'},
                 {'case': 'ternary sign input', 'error': 'no available backend accepts', 'op': 'is_skew'},
                 {'case': 'ternary sign input', 'error': 'no available backend accepts', 'op': 'is_regular'},
                 {'case': 'ternary sign input',
                  'error': 'no available backend accepts',
                  'op': 'is_conference'},
                 {'case': 'ternary sign input',
                  'error': 'no available backend accepts',
                  'op': 'canonical_form'},
                 {'case': 'canonical form with count',
                  'error': 'does not accept',
                  'op': 'canonical_form',
                  'reduction': 'count'}]},
 {'backends': [{'accepts': 'natural-number edge matrices with 2 <= uniformity <= vertices <= 64',
                'name': 'generic',
                'sources': ['backends/generic/hypergraphs_generic.cpp'],
                'summary': 'Portable C++: bit-set intersections, backtracking colourings and Berge paths, '
                           'and subset clique tests, threaded over family members.'}],
  'module': {'cases': 'cases.py',
             'contract': 'lean/Hypergraphs/Contract.lean',
             'lean': 'lean',
             'naive': 'naive/naive.py',
             'name': 'hypergraphs',
             'reference': 'lean/Hypergraphs/Reference.lean',
             'summary': 'Finite uniform hypergraphs on {0,...,n-1}: linearity, weak colouring number, exact '
                        'Berge-cycle tests and girth, clique-free Turan searches, and two-colour Ramsey '
                        'searches. Edges and vertices use increasing order; Berge girth is 0 when no cycle '
                        'exists.',
             'version': 1},
  'operations': [{'args': {'vertices': 'int'},
                  'families': ['explicit', 'subsets', 'subsets_of'],
                  'name': 'is_linear',
                  'summary': 'Whether every two distinct edges intersect in at most one vertex. '
                             'Equivalently, there is no Berge cycle of length 2.',
                  'value': 'boolean'},
                 {'args': {'vertices': 'int'},
                  'families': ['explicit', 'subsets', 'subsets_of'],
                  'name': 'colouring_number',
                  'summary': 'Weak vertex colouring number: the least positive number of colours for which '
                             'no edge is monochromatic.',
                  'value': 'integer'},
                 {'args': {'length': 'int', 'vertices': 'int'},
                  'families': ['explicit', 'subsets', 'subsets_of'],
                  'name': 'has_berge_cycle',
                  'summary': 'Whether there are `length` distinct vertices and distinct edges in cyclic '
                             'alternating order, each edge containing its two adjacent cycle vertices. '
                             'Length 2 is allowed.',
                  'value': 'boolean'},
                 {'args': {'vertices': 'int'},
                  'families': ['explicit', 'subsets', 'subsets_of'],
                  'name': 'berge_girth',
                  'summary': 'The least Berge-cycle length, including length 2; 0 when the hypergraph has no '
                             'Berge cycle.',
                  'value': 'integer'},
                 {'args': {'clique_size': 'int', 'vertices': 'int'},
                  'families': ['explicit', 'subsets', 'subsets_of'],
                  'name': 'is_clique_free',
                  'summary': "Whether no `clique_size` vertices contain every edge of the member's "
                             'uniformity. Searching fixed edge counts with `first` or `hits` gives exact '
                             'finite Turan bounds.',
                  'value': 'boolean'},
                 {'args': {'blue_clique': 'int', 'red_clique': 'int', 'vertices': 'int'},
                  'families': ['explicit', 'subsets', 'subsets_of'],
                  'name': 'is_ramsey_colouring',
                  'summary': "Treat the member's edges as red and every other edge of the same uniformity as "
                             'blue; true exactly when it has neither a red `red_clique` nor a blue '
                             '`blue_clique`.',
                  'value': 'boolean'}],
  'rejections': [{'case': 'finite-field edges', 'error': 'natural-number'},
                 {'case': 'noncanonical edges', 'error': 'strictly increasing'},
                 {'case': 'too many vertices', 'error': 'at most 64'},
                 {'case': 'Berge length one', 'error': 'at least 2'},
                 {'case': 'clique below uniformity', 'error': 'at least the uniformity'}]},
 {'backends': [{'accepts': 'partition and composition families whose size fits in 64 bits',
                'name': 'generic',
                'sources': ['backends/generic/integer_partitions_generic.cpp'],
                'summary': 'Portable C++: recursive family enumeration split by largest part or composition '
                           'length, with runtime integer reductions.'}],
  'module': {'cases': 'cases.py',
             'contract': 'lean/Integer_partitions/Contract.lean',
             'lean': 'lean',
             'naive': 'naive/naive.py',
             'name': 'integer_partitions',
             'reference': 'lean/Integer_partitions/Reference.lean',
             'summary': 'Constrained integer partitions and compositions. Families support odd, distinct, '
                        'largest-part, length and multiplicity bounds. Rank and crank are returned with the '
                        'partition total added, so histogram bin i represents statistic i-total.',
             'version': 1},
  'operations': [{'families': ['partitions', 'compositions'],
                  'name': 'number_of_parts',
                  'summary': 'Number of positive parts in the member. Histogram gives the length '
                             'distribution.',
                  'value': 'integer'},
                 {'families': ['partitions', 'compositions'],
                  'name': 'largest_part',
                  'summary': 'Largest positive part in the member. Histogram gives the largest-part '
                             'distribution.',
                  'value': 'integer'},
                 {'families': ['partitions'],
                  'name': 'rank',
                  'summary': 'Dyson rank (largest part minus number of parts), encoded by adding the '
                             'partition total. Histogram bin i counts rank i-total.',
                  'value': 'integer'},
                 {'families': ['partitions'],
                  'name': 'crank',
                  'summary': 'Andrews-Garvan crank, encoded by adding the partition total. If there are no '
                             'ones it is the largest part; otherwise it is parts greater than the number of '
                             'ones minus the number of ones. Histogram bin i counts crank i-total.',
                  'value': 'integer'}],
  'rejections': [{'case': 'compositions of 6', 'error': 'partitions families only', 'op': 'rank'},
                 {'case': 'compositions of 6', 'error': 'partitions families only', 'op': 'crank'}]},
 {'backends': [{'accepts': 'q >= 2 for formula operations; any matrix family over p < 2^32 for row-space '
                           'operations; integer answers must fit in u64',
                'name': 'generic',
                'sources': ['backends/generic/lattice_of_subspaces_generic.cpp'],
                'summary': 'Portable C++: checked Gaussian-binomial dynamic programming and per-member '
                           'incremental row reduction, threaded over canonical member ranges.'}],
  'module': {'cases': 'cases.py',
             'contract': 'lean/Lattice_of_subspaces/Contract.lean',
             'lean': 'lean',
             'naive': 'naive/naive.py',
             'name': 'lattice_of_subspaces',
             'reference': 'lean/Lattice_of_subspaces/Reference.lean',
             'summary': 'Counts in subspace lattices: Gaussian binomials, flags, subspaces above or below a '
                        'row space, and incidence with a fixed row space.',
             'version': 1},
  'operations': [{'args': {'n': 'int', 'q': 'int'},
                  'families': ['range'],
                  'name': 'gaussian_binomial',
                  'summary': 'For each k in a range, the Gaussian binomial [n choose k]_q, with value 0 for '
                             'k > n. q must be at least 2.',
                  'value': 'integer'},
                 {'args': {'n': 'int', 'q': 'int'},
                  'families': ['words'],
                  'name': 'flag_count',
                  'summary': 'For each dimension word d_1,...,d_s, the Gaussian product for strict flags '
                             'with dim V_i = d_i. When q is a prime power this counts such flags in an '
                             'n-space over F_q. The value is 0 unless the dimensions strictly increase and '
                             'are at most n; q must be at least 2.',
                  'value': 'integer'},
                 {'args': {'h': 'int'},
                  'families': ['explicit',
                               'subsets',
                               'grassmannian',
                               'all_matrices',
                               'symmetric_matrices',
                               'transform',
                               'stack',
                               'subsets_of'],
                  'name': 'contained_subspace_count',
                  'summary': "Number of h-dimensional subspaces contained in the member's row space. A "
                             'member denotes its row space, even when its rows are dependent.',
                  'value': 'integer'},
                 {'args': {'h': 'int'},
                  'families': ['explicit',
                               'subsets',
                               'grassmannian',
                               'all_matrices',
                               'symmetric_matrices',
                               'transform',
                               'stack',
                               'subsets_of'],
                  'name': 'containing_subspace_count',
                  'summary': 'Number of h-dimensional subspaces of the ambient F_p^n that contain the '
                             "member's row space. A member denotes its row space, even when its rows are "
                             'dependent.',
                  'value': 'integer'},
                 {'args': {'subspace': 'vectors'},
                  'families': ['explicit',
                               'subsets',
                               'grassmannian',
                               'all_matrices',
                               'symmetric_matrices',
                               'transform',
                               'stack',
                               'subsets_of'],
                  'name': 'contains',
                  'summary': "Whether the member's row space contains the row space spanned by `subspace`.",
                  'value': 'boolean'},
                 {'args': {'subspace': 'vectors'},
                  'families': ['explicit',
                               'subsets',
                               'grassmannian',
                               'all_matrices',
                               'symmetric_matrices',
                               'transform',
                               'stack',
                               'subsets_of'],
                  'name': 'is_contained_in',
                  'summary': "Whether the member's row space is contained in the row space spanned by "
                             '`subspace`.',
                  'value': 'boolean'}],
  'rejections': [{'case': 'q below two', 'error': 'q must be at least 2'},
                 {'case': 'flag count on a range', 'error': 'defined on words families only'},
                 {'case': 'wrong subspace width', 'error': 'same number of columns'}]},
 {'backends': [{'accepts': 'square nonnegative integer matrices; symmetric matrices for spanning_tree_count; '
                           'perfect matching by Gray-code Ryser below 63 rows, spanning trees by the '
                           'matrix-tree determinant, max flow by Edmonds-Karp; results must fit u64',
                'name': 'generic',
                'sources': ['backends/generic/matchings_and_flows_generic.cpp'],
                'summary': 'Portable C++ with exact arbitrary-precision permanent and determinant '
                           'arithmetic, an integer residual network for max flow, and parallel evaluation '
                           'across family members.'}],
  'module': {'cases': 'cases.py',
             'contract': 'lean/Matchings_and_flows/Contract.lean',
             'lean': 'lean',
             'naive': 'naive/naive.py',
             'name': 'matchings_and_flows',
             'reference': 'lean/Matchings_and_flows/Reference.lean',
             'summary': 'Exact weighted perfect-matching counts, weighted undirected spanning-tree counts, '
                        'and directed maximum-flow values for families of nonnegative integer matrices. '
                        'Every result must fit u64.',
             'version': 1},
  'operations': [{'name': 'perfect_matching_count',
                  'summary': 'The permanent of a square matrix A: sum over bijections sigma of product_i '
                             'A[i,sigma(i)]. Equivalently, the number of perfect matchings in the bipartite '
                             'multigraph with A[i,j] parallel edges.',
                  'value': 'integer'},
                 {'name': 'spanning_tree_count',
                  'summary': 'For a square symmetric matrix A, the weighted count of undirected spanning '
                             'trees: sum over trees T of product_{i<j in T} A[i,j]. Diagonal entries are '
                             'ignored. Asymmetric members make the request invalid.',
                  'value': 'integer'},
                 {'args': {'sink': 'int', 'source': 'int'},
                  'name': 'max_flow',
                  'summary': 'Maximum integral directed flow from source to sink in the square capacity '
                             'matrix A. Loops are ignored. Source and sink are zero-based distinct vertex '
                             'indices.',
                  'value': 'integer'}],
  'rejections': [{'case': 'rectangular perfect matching', 'error': 'square matrices'},
                 {'case': 'rectangular spanning tree', 'error': 'square matrices'},
                 {'case': 'asymmetric spanning tree', 'error': 'symmetric'},
                 {'case': 'equal flow terminals', 'error': 'distinct'},
                 {'case': 'flow terminal outside graph', 'error': 'vertex indices'},
                 {'case': 'binary 2x2 perfect matchings',
                  'error': 'does not accept integer',
                  'op': 'perfect_matching_count',
                  'reduction': 'count'}]},
 {'backends': [{'accepts': 'subsets of flattened n x n matrices over any prime p < 2^32',
                'name': 'generic',
                'sources': ['backends/generic/matrix_groups_generic.cpp'],
                'summary': 'Portable C++: group order by a Schreier stabilizer chain on basis vectors; '
                           'invariant-subspace, commuting-algebra, invariant-form, and block-system searches '
                           'by finite-field elimination. Members run in parallel.'}],
  'module': {'cases': 'cases.py',
             'contract': 'lean/Matrix_groups/Contract.lean',
             'lean': 'lean',
             'naive': 'naive/naive.py',
             'name': 'matrix_groups',
             'reference': 'lean/Matrix_groups/Reference.lean',
             'summary': 'Structure of matrix groups over F_p supplied as subsets of a generator dictionary: '
                        'order, irreducibility, absolute irreducibility, invariant bilinear forms, and '
                        'imprimitivity. Vectors act on the right.',
             'version': 1},
  'operations': [{'families': ['subsets'],
                  'name': 'order',
                  'summary': "Order of the subgroup of GL(n,p) generated by the member's flattened n x n "
                             'matrices.',
                  'value': 'integer'},
                 {'families': ['subsets'],
                  'name': 'is_irreducible',
                  'summary': 'Whether F_p^n has no nonzero proper subspace invariant under every generator.',
                  'value': 'boolean'},
                 {'families': ['subsets'],
                  'name': 'is_absolutely_irreducible',
                  'summary': 'Whether the representation stays irreducible over an algebraic closure. '
                             'Equivalently here: it is irreducible and its commuting algebra consists only '
                             'of scalar matrices.',
                  'value': 'boolean'},
                 {'families': ['subsets'],
                  'name': 'preserves_form',
                  'summary': 'Whether there is a nondegenerate bilinear form B with A B A^T = B for every '
                             'generator A, using the right-row action v -> v A.',
                  'value': 'boolean'},
                 {'families': ['subsets'],
                  'name': 'is_imprimitive',
                  'summary': 'Whether the group is irreducible and permutes a direct-sum decomposition into '
                             'more than one equal-dimensional proper subspace.',
                  'value': 'boolean'}],
  'rejections': [{'case': 'explicit generators', 'error': 'subsets families only'},
                 {'case': 'nonsquare dictionary', 'error': 'perfect square'},
                 {'case': 'singular dictionary', 'error': 'not an invertible'}]},
 {'backends': [{'accepts': 'any group given by generators; orbits computed by breadth-first search per '
                           'member; group order by closure up to 2^26 elements',
                'name': 'generic',
                'sources': ['backends/generic/orbits_generic.cpp'],
                'summary': 'Portable C++: per-member orbit BFS over the generators with index ranking '
                           "through the family's unrank/rank, threaded over members; fixed_points on subsets "
                           'by cycle type (coefficient of x^k in the product of 1 + x^len over cycles). No '
                           'orderly-generation pruning yet.'}],
  'kinds': [{'lean': 'perm',
             'name': 'orbits.perms',
             'params': ['n', 'count'],
             'payload': 'count*n u32 point indices; element g maps point i to entry g*n+i',
             'summary': 'A batch of `count` permutations of {0..n-1}. As a group argument, the generators.'}],
  'module': {'cases': 'cases.py',
             'contract': 'lean/Orbits/Contract.lean',
             'lean': 'lean',
             'naive': 'naive/naive.py',
             'name': 'orbits',
             'reference': 'lean/Orbits/Reference.lean',
             'summary': 'Finite permutation and matrix groups acting on families: canonical representatives, '
                        'orbit sizes, stabilisers, fixed points (Burnside), induced point actions.',
             'version': 1},
  'operations': [{'args': {'group': 'group'},
                  'families': ['subsets', 'subsets_of', 'grassmannian', 'all_matrices'],
                  'name': 'is_canonical',
                  'summary': 'The member has the least index in its orbit under `group`. With `hits`, the '
                             'orbit transversal; with `count`, the number of orbits.',
                  'value': 'boolean'},
                 {'args': {'group': 'group'},
                  'families': ['subsets', 'subsets_of', 'grassmannian', 'all_matrices'],
                  'name': 'canonical_index',
                  'summary': "The least index in the member's orbit under `group`.",
                  'value': 'integer'},
                 {'args': {'group': 'group'},
                  'families': ['subsets', 'subsets_of', 'grassmannian', 'all_matrices'],
                  'name': 'orbit_size',
                  'summary': 'Number of members in the orbit of the member under `group`.',
                  'value': 'integer'},
                 {'args': {'group': 'group'},
                  'families': ['subsets', 'subsets_of', 'grassmannian', 'all_matrices'],
                  'name': 'stabilizer_order',
                  'summary': 'Order of the stabiliser of the member in `group`, i.e. |group| / orbit_size. '
                             'Needs the group order, so `group` must generate a group the backend can '
                             'enumerate.',
                  'value': 'integer'},
                 {'args': {'on': 'family'},
                  'families': ['group_elements'],
                  'name': 'fixed_points',
                  'summary': 'For each group element, the number of members of the family `on` it fixes. Sum '
                             'over the group divided by the group order is the number of orbits (Burnside), '
                             'an independent check of is_canonical/count.',
                  'value': 'integer'},
                 {'args': {'points': 'vectors'},
                  'families': ['explicit'],
                  'name': 'projective_action',
                  'summary': 'For each n x n matrix A of the batch, the permutation of the projective points '
                             '`points` (a dictionary of 1 x n rows, each scaled so its first nonzero entry '
                             'is 1, pairwise distinct) induced by v -> normalise(v A). Fails if the '
                             'dictionary is not closed under some A. Bridges matrix groups to `subsets` '
                             'families over projective points.',
                  'value': 'orbits.perms'}],
  'rejections': [{'case': 'C5 on the hexagon', 'error': 'cannot act on a dictionary'},
                 {'case': 'perms on a Grassmannian', 'error': 'subsets'},
                 {'case': '2x2 matrices on PG(2,2)', 'error': 'n x n'},
                 {'case': 'singular matrix on PG(1,2)', 'error': 'singular'},
                 {'case': 'points not closed', 'error': 'outside the dictionary'},
                 {'case': 'D6 on 2-subsets',
                  'error': 'does not accept',
                  'op': 'is_canonical',
                  'reduction': 'histogram'},
                 {'case': 'fixed_points on a subsets family', 'error': 'families'}]},
 {'backends': [{'accepts': 'permutation-valued subsets and explicit families; group orders fitting in u64',
                'name': 'generic',
                'sources': ['backends/generic/perm_groups_generic.cpp'],
                'summary': 'Portable C++ Schreier-Sims stabilizer chains, parallel over family members; no '
                           'group closure for order or membership.'}],
  'kinds': [{'lean': 'partition',
             'name': 'perm_groups.partition',
             'params': ['count', 'n'],
             'payload': "count*n u32 labels; label i is the least point in i's orbit",
             'summary': 'One point-orbit partition per group, encoded by the least point in each orbit.'},
            {'lean': 'bsgs',
             'name': 'perm_groups.bsgs',
             'params': ['count', 'n'],
             'payload': 'u64 base_offsets[count+1], u64 strong_offsets[count+1], then u32 base points, then '
                        'strong permutations (n u32 entries each)',
             'summary': 'Per group: a greedy base and one lexicographically sorted strong generating set.'}],
  'module': {'cases': 'cases.py',
             'contract': 'lean/Perm_groups/Contract.lean',
             'lean': 'lean',
             'naive': 'naive/naive.py',
             'name': 'perm_groups',
             'reference': 'lean/Perm_groups/Reference.lean',
             'summary': 'Schreier-Sims for permutation groups: order, membership, transitivity, primitivity, '
                        'point orbits, and a deterministic base with strong generators. A group member is a '
                        'nonempty matrix of permutation rows. Use `subsets` on an `orbits.perms` dictionary '
                        'for every k-generated subgroup, or select the full dictionary for one explicit '
                        'group. Point-orbit labels are their least points. The BSGS uses the least moved '
                        'point at each level, sorted generators, breadth-first Schreier transversals, and '
                        'lexicographically sorted deduplicated strong generators.',
             'version': 1},
  'operations': [{'families': ['subsets', 'explicit'],
                  'name': 'order',
                  'summary': "Order of the group generated by the member's permutation rows, computed from "
                             'the stabilizer-chain orbit sizes.',
                  'value': 'integer'},
                 {'args': {'target': 'perms'},
                  'families': ['subsets', 'explicit'],
                  'name': 'contains',
                  'summary': 'Whether the group contains `target`, which must contain exactly one '
                             'permutation of the same degree.',
                  'value': 'boolean'},
                 {'families': ['subsets', 'explicit'],
                  'name': 'is_transitive',
                  'summary': 'Whether the generated group is transitive on 0..n-1.',
                  'value': 'boolean'},
                 {'families': ['subsets', 'explicit'],
                  'name': 'is_primitive',
                  'summary': 'Whether the generated group is transitive and preserves no nontrivial '
                             'partition of 0..n-1.',
                  'value': 'boolean'},
                 {'families': ['subsets', 'explicit'],
                  'name': 'orbit_partition',
                  'summary': 'Point-orbit labels: point i is labelled by the least point in its orbit.',
                  'value': 'perm_groups.partition'},
                 {'families': ['subsets', 'explicit'],
                  'name': 'base_and_strong_generators',
                  'summary': 'A deterministic BSGS. Repeatedly choose the least point moved by the current '
                             'stabilizer; use sorted generators and breadth-first Schreier transversals; '
                             'return the union of level generators sorted lexicographically with duplicates '
                             'and identity removed.',
                  'value': 'perm_groups.bsgs'}],
  'rejections': [{'case': 'matrix rows are not permutations', 'error': 'permutation rows'},
                 {'case': 'two membership targets', 'error': 'exactly one permutation'},
                 {'case': 'wrong-degree membership target', 'error': 'same degree'}]},
 {'backends': [{'accepts': 'subsets of coordinate rows over any prime p < 2^32; line and hyperplane '
                           'incidence is precomputed once per request',
                'name': 'generic',
                'sources': ['backends/generic/projective_sets_generic.cpp'],
                'summary': 'Portable C++: precomputes dictionary incidence with every line or hyperplane, '
                           'then evaluates members in parallel.'}],
  'module': {'cases': 'cases.py',
             'contract': 'lean/Projective_sets/Contract.lean',
             'lean': 'lean',
             'naive': 'naive/naive.py',
             'name': 'projective_sets',
             'reference': 'lean/Projective_sets/Reference.lean',
             'summary': 'Point sets in PG(n,p), given as subsets of distinct normalised nonzero coordinate '
                        'rows over F_p. Arc means every n+1 points are independent; cap means no three are '
                        'collinear. Secant, tangent and passant counts range over every projective line.',
             'version': 1},
  'operations': [{'families': ['subsets'],
                  'name': 'is_arc',
                  'summary': 'Whether every n+1 selected points of PG(n,p) are linearly independent, '
                             'equivalently every hyperplane contains at most n points.',
                  'value': 'boolean'},
                 {'families': ['subsets'],
                  'name': 'is_cap',
                  'summary': 'Whether no projective line contains three selected points.',
                  'value': 'boolean'},
                 {'families': ['subsets'],
                  'name': 'is_blocking_set',
                  'summary': 'Whether the set meets every projective hyperplane.',
                  'value': 'boolean'},
                 {'families': ['subsets'],
                  'name': 'is_hyperoval',
                  'summary': 'Whether the set is a 4-point cap in PG(2,2), the only even field supported by '
                             'the prime-field runtime.',
                  'value': 'boolean'},
                 {'families': ['subsets'],
                  'name': 'is_ovoid',
                  'summary': 'Whether the set is a cap of p^2+1 points in PG(3,p).',
                  'value': 'boolean'},
                 {'families': ['subsets'],
                  'name': 'max_collinear',
                  'summary': 'The largest intersection with a projective line; 0 when the ambient space has '
                             'no lines.',
                  'value': 'integer'},
                 {'families': ['subsets'],
                  'name': 'spanned_rank',
                  'summary': 'Vector-space rank of the selected homogeneous coordinate rows, one more than '
                             'the projective dimension of a nonempty span.',
                  'value': 'integer'},
                 {'families': ['subsets'],
                  'name': 'secant_count',
                  'summary': 'Number of projective lines containing exactly two selected points.',
                  'value': 'integer'},
                 {'families': ['subsets'],
                  'name': 'tangent_count',
                  'summary': 'Number of projective lines containing exactly one selected point.',
                  'value': 'integer'},
                 {'families': ['subsets'],
                  'name': 'passant_count',
                  'summary': 'Number of projective lines containing no selected point.',
                  'value': 'integer'}],
  'rejections': [{'case': 'explicit point set', 'error': 'subsets'},
                 {'case': 'zero projective point', 'error': 'contains zero'},
                 {'case': 'unnormalised projective point', 'error': 'not normalised'},
                 {'case': 'duplicate projective point', 'error': 'contains a duplicate'}]},
 {'backends': [{'accepts': 'any modulus below 2^32; ranges of residues or of moduli',
                'name': 'generic',
                'sources': ['backends/generic/residues_generic.cpp'],
                'summary': 'Portable C++: factors the modulus and phi(n) once per request, then answers each '
                           'member with modular exponentiation; discrete logarithms use baby-step giant-step '
                           'over a baby table shared by every member, after the standard reduction that '
                           'removes the common factors of a non-unit base; the Jacobi symbol uses quadratic '
                           'reciprocity.'}],
  'module': {'cases': 'cases.py',
             'contract': 'lean/Residues/Contract.lean',
             'lean': 'lean',
             'naive': 'naive/naive.py',
             'name': 'residues',
             'reference': 'lean/Residues/Reference.lean',
             'summary': 'Arithmetic in Z/n over ranges of residues: multiplicative order, primitive roots, '
                        'quadratic residues, discrete logarithms and the Legendre and Jacobi symbols. '
                        'Members of a `range` family are residues reduced modulo the `modulus` argument, '
                        'except `least_primitive_root`, whose member is the modulus. Canonical answers where '
                        'mathematics leaves a choice: an order is 0 when the residue is not a unit; a '
                        'discrete logarithm is the least x < n, and the modulus itself when there is none; a '
                        'symbol is 0, 1, or 2 with 2 standing for -1; the least primitive root is 0 when '
                        '(Z/n)* is not cyclic.',
             'version': 1},
  'operations': [{'args': {'modulus': 'int'},
                  'families': ['range'],
                  'name': 'multiplicative_order',
                  'summary': 'The least k >= 1 with a^k = 1 in Z/n for the member a, and 0 when a is not a '
                             'unit.',
                  'value': 'integer'},
                 {'args': {'modulus': 'int'},
                  'families': ['range'],
                  'name': 'is_primitive_root',
                  'summary': 'Whether the member generates the unit group of Z/n: a unit whose '
                             'multiplicative order is phi(n).',
                  'value': 'boolean'},
                 {'args': {'modulus': 'int'},
                  'families': ['range'],
                  'name': 'is_quadratic_residue',
                  'summary': 'Whether the member is a unit of Z/n with a square root there. Non-units, '
                             'including 0, are not quadratic residues.',
                  'value': 'boolean'},
                 {'args': {'base': 'int', 'modulus': 'int'},
                  'families': ['range'],
                  'name': 'discrete_log',
                  'summary': 'The least x with 0 <= x < n and base^x = a in Z/n for the member a; n itself '
                             'when no such x exists. Any solution is smaller than n, so the modulus is '
                             'unambiguous as the absent answer.',
                  'value': 'integer'},
                 {'args': {'modulus': 'int'},
                  'families': ['range'],
                  'name': 'legendre',
                  'summary': 'The Legendre symbol (a/p) of the member for an odd prime modulus p, encoded 0 '
                             'for 0, 1 for 1, and 2 for -1.',
                  'value': 'integer'},
                 {'args': {'modulus': 'int'},
                  'families': ['range'],
                  'name': 'jacobi',
                  'summary': 'The Jacobi symbol (a/n) of the member for an odd modulus n, the product of the '
                             'Legendre symbols over the prime factorisation of n, in the same 0, 1, 2 '
                             'encoding. (a/1) is 1.',
                  'value': 'integer'},
                 {'families': ['range'],
                  'name': 'least_primitive_root',
                  'summary': 'Reads the member as a modulus n >= 1: the least g >= 1 that generates the unit '
                             'group of Z/n, and 0 when (Z/n)* is not cyclic. It is 1 for n = 1 and n = 2.',
                  'value': 'integer'}],
  'rejections': [{'case': 'not a range', 'error': 'range families only'},
                 {'case': 'modulus zero', 'error': 'modulus of at least 1'},
                 {'case': 'modulus too large', 'error': 'modulus less than'},
                 {'case': 'even legendre modulus', 'error': 'odd prime'},
                 {'case': 'composite legendre modulus', 'error': 'odd prime'},
                 {'case': 'even jacobi modulus', 'error': 'odd modulus'},
                 {'case': 'moduli from zero', 'error': 'moduli of at least 1'}]},
 {'backends': [{'accepts': "subsets_of(words(2,n),m); n <= 22 follows from the runtime's materialisation "
                           'limit',
                'name': 'generic',
                'sources': ['backends/generic/set_systems_generic.cpp'],
                'summary': 'Portable C++: depth-first outer-subset enumeration, pruning a subtree as soon as '
                           'its prefix violates an intersection, antichain, sunflower, EKR, or Sperner '
                           'predicate; incremental degrees and lower shadows.'}],
  'module': {'cases': 'cases.py',
             'contract': 'lean/Set_systems/Contract.lean',
             'lean': 'lean',
             'naive': 'naive/naive.py',
             'name': 'set_systems',
             'reference': 'lean/Set_systems/Reference.lean',
             'summary': 'Extremal predicates on m-set systems represented by subsets_of(words(2,n),m): '
                        'intersection, antichains, sunflowers, degree, lower shadow, and exact EKR/Sperner '
                        'extremality checks.',
             'version': 1},
  'operations': [{'families': ['subsets_of'],
                  'name': 'is_intersecting',
                  'summary': 'Every two distinct sets in the system intersect. A one-set system is '
                             'intersecting.',
                  'value': 'boolean'},
                 {'families': ['subsets_of'],
                  'name': 'is_antichain',
                  'summary': 'No two distinct sets in the system contain one another.',
                  'value': 'boolean'},
                 {'args': {'k': 'int'},
                  'families': ['subsets_of'],
                  'name': 'is_sunflower_free',
                  'summary': 'The system contains no k distinct sets whose pairwise intersections are all '
                             'equal; k must be at least 2.',
                  'value': 'boolean'},
                 {'families': ['subsets_of'],
                  'name': 'max_degree',
                  'summary': 'Maximum, over ground elements, of the number of sets containing that element.',
                  'value': 'integer'},
                 {'families': ['subsets_of'],
                  'name': 'shadow_size',
                  'summary': 'Cardinality of the lower shadow: the union of all sets obtained by deleting '
                             'one element from one member set.',
                  'value': 'integer'},
                 {'families': ['subsets_of'],
                  'name': 'is_ekr_extremal',
                  'summary': 'True exactly for a nonempty r-uniform intersecting system on n points with r '
                             '>= 1, n >= 2r, and size C(n-1,r-1).',
                  'value': 'boolean'},
                 {'families': ['subsets_of'],
                  'name': 'is_sperner_extremal',
                  'summary': 'True exactly for an antichain on n points of size C(n,floor(n/2)).',
                  'value': 'boolean'}],
  'rejections': [{'case': 'subsets of integers', 'error': 'family of the form'},
                 {'case': 'ternary words', 'error': 'family of the form'},
                 {'case': 'sunflower k=1', 'error': 'k must be at least 2'}]},
 {'backends': [{'accepts': 'Any p < 2^32 and Grassmannian-derived transform/stack family whose ambient '
                           'Grassmannian size at each encountered rank fits u64; group closure up to 2^26 '
                           'elements.',
                'name': 'generic',
                'sources': ['backends/generic/subspace_orbits_generic.cpp'],
                'summary': 'Portable C++: canonical rref and breadth-first orbit search per member, threaded '
                           'over family members.'}],
  'module': {'cases': 'cases.py',
             'contract': 'lean/Subspace_orbits/Contract.lean',
             'lean': 'lean',
             'naive': 'naive/naive.py',
             'name': 'subspace_orbits',
             'reference': 'lean/Subspace_orbits/Reference.lean',
             'summary': 'GL and projective linear orbits of Grassmannian families and their transform/stack '
                        'derivatives. Representatives are the least rref subspaces in Grassmannian order. '
                        'Set projective=0 for the generated GL group and projective=1 for its image modulo '
                        "nonzero scalars. Over the runtime's prime fields, PGammaL equals PGL.",
             'version': 1},
  'operations': [{'args': {'group': 'group', 'projective': 'int'},
                  'families': ['grassmannian', 'transform', 'stack'],
                  'name': 'is_canonical',
                  'summary': "Whether the member's row space is the least subspace in its orbit. Subspaces "
                             "are ordered by their canonical rref's index in grassmannian(p, n, rank).",
                  'value': 'boolean'},
                 {'args': {'group': 'group', 'projective': 'int'},
                  'families': ['grassmannian', 'transform', 'stack'],
                  'name': 'canonical_index',
                  'summary': 'Index of the least orbit representative in grassmannian(p, n, rank), where '
                             "rank and n belong to this member's row space.",
                  'value': 'integer'},
                 {'args': {'group': 'group', 'projective': 'int'},
                  'families': ['grassmannian', 'transform', 'stack'],
                  'name': 'orbit_size',
                  'summary': "Number of distinct row spaces in the member's orbit. The projective flag does "
                             'not change the orbit.',
                  'value': 'integer'},
                 {'args': {'group': 'group', 'projective': 'int'},
                  'families': ['grassmannian', 'transform', 'stack'],
                  'name': 'stabilizer_order',
                  'summary': 'Order of the stabilizer: |generated GL group|/orbit_size when projective=0, or '
                             '|its image modulo nonzero scalars|/orbit_size when projective=1.',
                  'value': 'integer'}],
  'rejections': [{'case': 'permutations on subspaces', 'error': 'gfp.matrix'},
                 {'case': 'all matrices are not a subspace family', 'error': 'families only'},
                 {'case': 'wrong group dimension', 'error': 'n x n'},
                 {'case': 'singular generator', 'error': 'invertible'},
                 {'case': 'invalid projective flag', 'error': 'projective'}]},
 {'backends': [{'accepts': 'partition operations through n=30; RSK when its materialised output has at most '
                           '2^31 u32 entries; any representable standard_tableaux family',
                'name': 'generic',
                'sources': ['backends/generic/young_generic.cpp'],
                'summary': 'Portable C++: hook products, row-insertion RSK, recursive semistandard fillings, '
                           'and memoised Murnaghan-Nakayama over subpartitions. Members run in parallel.'}],
  'kinds': [{'lean': 'character',
             'name': 'young.characters',
             'params': ['count'],
             'payload': 'count signed i64 character values',
             'summary': 'One signed Murnaghan-Nakayama character value per member.'},
            {'lean': 'rsk',
             'name': 'young.rsk_pairs',
             'params': ['count', 'length'],
             'payload': 'count*length u32 row lengths, then two count*length*length u32 padded tableaux',
             'summary': 'For each word, its common shape padded to length entries, followed by the insertion '
                        'and recording tableaux padded to length x length squares.'}],
  'module': {'cases': 'cases.py',
             'contract': 'lean/Young/Contract.lean',
             'lean': 'lean',
             'naive': 'naive/naive.py',
             'name': 'young',
             'reference': 'lean/Young/Reference.lean',
             'summary': 'Partitions and standard Young tableaux with hook-length counts, Kostka numbers, '
                        'row-insertion RSK, and signed S_n character values from Murnaghan-Nakayama. '
                        'Partitions are descending lexicographically; tableaux recursively place the largest '
                        'entry in removable corners from top to bottom; RSK bumps the first strictly larger '
                        'row entry.',
             'version': 1},
  'operations': [{'args': {'weight': 'vector'},
                  'families': ['partitions'],
                  'name': 'kostka',
                  'summary': 'Kostka number K_shape,weight: semistandard tableaux with weak rows, strict '
                             'columns, and weight[i] copies of i.',
                  'value': 'integer'},
                 {'families': ['words'],
                  'name': 'rsk',
                  'summary': 'Robinson-Schensted-Knuth row insertion. Letters retain their 0-based values; '
                             'recording entries are 1..length; the first row entry strictly greater than the '
                             'inserted letter is bumped.',
                  'value': 'young.rsk_pairs'},
                 {'args': {'cycle_type': 'vector'},
                  'families': ['partitions'],
                  'name': 'murnaghan_nakayama',
                  'summary': 'The irreducible S_n character indexed by each shape at the positive weakly '
                             'decreasing cycle type, computed by Murnaghan-Nakayama. Signed values use '
                             "little-endian two's-complement i64.",
                  'value': 'young.characters'},
                 {'families': ['partitions', 'standard_tableaux'],
                  'name': 'hook_length_count',
                  'summary': "Number of standard Young tableaux of the member's shape. On a "
                             "standard_tableaux family, every member has the family's fixed shape.",
                  'value': 'integer'}],
  'rejections': [{'case': 'bad Kostka weight', 'error': 'weight must sum'},
                 {'case': 'bad cycle type',
                  'error': 'cycle_type must be a positive weakly decreasing partition'},
                 {'case': 'RSK on partitions', 'error': 'words families only'}]}]
