"""simplicial_complexes cases: the inputs the harness runs against the backend, the naive
implementation and the Lean reference.

Members are 0/1 matrices over F_2. A row is a set of vertices; `nonfaces=0` reads the rows as
faces that generate the complex and `nonfaces=1` reads them as forbidden sets, which turns a
family of graphs (rows of weight two) into a family of independence complexes.

Oracle cases are sized for the Lean kernel (a few dozen members, at most six or seven vertices);
bench cases are sized to show what the kernel does.
"""
from __future__ import annotations

import itertools
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
import lemmakernel as lk  # noqa: E402
from tools.harness import Case, module, rotate  # noqa: E402

OPS = ["f_count", "faces", "euler_characteristic", "betti", "is_shellable"]


def sets(n: int, subsets) -> lk.interchange.Matrix:
    """The given vertex sets as 0/1 rows on n vertices."""
    return lk.matrix(2, [[int(v in S) for v in range(n)] for S in subsets])


def uniform(n: int, k: int, count: int | None = None) -> lk.interchange.Matrix:
    """The first `count` k-subsets of n vertices, as rows."""
    return sets(n, list(itertools.combinations(range(n), k))[:count])


def edges(n: int, count: int | None = None) -> lk.interchange.Matrix:
    """The edges of the complete graph on n vertices, as weight-two rows."""
    return uniform(n, 2, count)


# The 6-vertex triangulation of the real projective plane (Moebius-Kantor), the octahedron
# (a 2-sphere), a hollow triangle (a circle), a solid triangle and two disjoint edges: five
# complexes whose homology over F_2 and over F_3 differs in the ways the module exists to show.
RP2 = [(0, 1, 2), (0, 2, 3), (0, 3, 4), (0, 4, 5), (0, 1, 5), (1, 2, 4), (2, 3, 5), (3, 4, 1),
       (4, 5, 2), (5, 1, 3)]
OCTAHEDRON = [(0, 2, 4), (0, 2, 5), (0, 3, 4), (0, 3, 5), (1, 2, 4), (1, 2, 5), (1, 3, 4), (1, 3, 5)]
CIRCLE = [(0, 1), (1, 2), (0, 2)]
SOLID = [(0, 1, 2)]
TWO_EDGES = [(0, 1), (2, 3)]


def surfaces(ctx):
    """One explicit family whose members are those five complexes, on six vertices."""
    rows = max(len(c) for c in (RP2, OCTAHEDRON, CIRCLE, SOLID, TWO_EDGES))
    batch = []
    for facets in (RP2, OCTAHEDRON, CIRCLE, SOLID, TWO_EDGES):
        padded = list(facets) + [facets[0]] * (rows - len(facets))  # repeat a facet to pad
        batch.append([[int(v in S) for v in range(6)] for S in padded])
    return ctx.explicit(lk.matrix(2, batch))


def cases(ctx, rng):
    del rng
    mod = module("simplicial_complexes")
    out = []

    def add(name, family, nonfaces, dim=1, p=2, reductions=lambda op, i: None):
        for j, op in enumerate(OPS):
            args = {"nonfaces": nonfaces, "dim": dim, "p": p, "limit": 3}
            out.append(Case(name, family, op, args, reductions=reductions(op, j)))

    # Complexes generated by two triangles of five vertices: every operation, every reduction.
    add("triangles on 5 vertices", ctx.subsets(uniform(5, 3, 6), 2), 0)

    # Independence complexes of the graphs with three of the six edges of K_4.
    add("independence complexes of 3-edge graphs", ctx.subsets(edges(4), 3), 1,
        reductions=lambda op, j: rotate(mod, op, j))

    # Five named complexes, including RP^2 over F_2 (where beta_1 = 1) and over F_3 (where it is 0).
    add("surfaces", surfaces(ctx), 0, dim=1, p=2, reductions=lambda op, j: rotate(mod, op, j + 1))
    out.append(Case("surfaces over F_3", surfaces(ctx), "betti",
                    {"nonfaces": 0, "dim": 1, "p": 3}, reductions=["all"]))
    out.append(Case("surfaces over F_3", surfaces(ctx), "betti",
                    {"nonfaces": 0, "dim": 2, "p": 3}, reductions=["histogram"]))
    out.append(Case("surfaces top homology", surfaces(ctx), "betti",
                    {"nonfaces": 0, "dim": 2, "p": 2}, reductions=["all"]))
    out.append(Case("surfaces euler over F_65537", surfaces(ctx), "euler_characteristic",
                    {"nonfaces": 0, "p": 65537}, reductions=["all"]))

    # Every family kind the runtime offers, at a size Lean evaluates in seconds.
    add("symmetric matrices as complexes", ctx.symmetric_matrices(2, 3), 0,
        reductions=lambda op, j: rotate(mod, op, j + 2))
    add("all 2x3 matrices as complexes", ctx.all_matrices(2, 2, 3), 1,
        reductions=lambda op, j: rotate(mod, op, j + 3))
    add("pairs of projective points", ctx.subsets_of(ctx.grassmannian(2, 3, 1), 2), 1,
        reductions=lambda op, j: rotate(mod, op, j + 4))
    add("triangles stacked on an edge", ctx.stack(ctx.subsets(uniform(4, 3), 2), lk.matrix(2, [[1, 1, 0, 0]])), 0,
        reductions=lambda op, j: rotate(mod, op, j))
    add("graphs through a linear map", ctx.transform(ctx.subsets(edges(4), 2), lk.matrix(2, [
        [1, 0, 0, 0, 1], [0, 1, 0, 0, 1], [0, 0, 1, 0, 0], [0, 0, 0, 1, 0]])), 1,
        reductions=lambda op, j: rotate(mod, op, j + 1))

    # Requests the runtime must refuse.
    out += [
        Case("graphs over F_3", ctx.all_matrices(3, 2, 3), "faces", {"nonfaces": 0}, oracle=False),
        Case("nonfaces flag out of range", ctx.subsets(uniform(4, 3), 2), "faces",
             {"nonfaces": 2}, oracle=False),
        Case("composite modulus", ctx.subsets(uniform(4, 3), 2), "betti",
             {"nonfaces": 0, "dim": 1, "p": 6}, oracle=False),
    ]

    # Benchmarks: requests that look like real use, sized so that the ratio shows.
    out += [
        Case("independence_betti", lambda: ctx.subsets(edges(7), 7), "betti",
             {"nonfaces": 1, "p": 2, "dim": 1},
             what="first Betti number over F_2 of the independence complex of every 7-edge graph on 7 vertices",
             bench="histogram", oracle=False),
        Case("independence_faces", lambda: ctx.subsets(edges(8), 7), "faces", {"nonfaces": 1},
             what="how many independent sets the 8-vertex graphs with 7 edges have",
             bench="max", oracle=False),
        Case("triangle_complexes_shellable", lambda: ctx.subsets(uniform(6, 3), 5), "is_shellable",
             {"nonfaces": 0, "limit": 4},
             what="how many of the complexes generated by five triangles of six vertices are shellable",
             bench="count", oracle=False),
        Case("clique_complex_homology", lambda: ctx.subsets(uniform(7, 3, 21), 5), "betti",
             {"nonfaces": 0, "p": 3, "dim": 1},
             what="first Betti number over F_3 of every complex generated by five of 21 triangles on seven vertices",
             bench="histogram", oracle=False),
    ]
    return out


def invariants(ctx):
    """Cross-operation identities on inputs beyond the kernel oracle."""
    family = surfaces(ctx)
    # RP^2 has 2-torsion: beta_1 is 1 over F_2 and 0 over F_3, and beta_2 the other way round.
    beta1_2 = ctx.value("simplicial_complexes.betti", family, "all", p=2, dim=1, nonfaces=0).values
    beta1_3 = ctx.value("simplicial_complexes.betti", family, "all", p=3, dim=1, nonfaces=0).values
    beta2_2 = ctx.value("simplicial_complexes.betti", family, "all", p=2, dim=2, nonfaces=0).values
    beta2_3 = ctx.value("simplicial_complexes.betti", family, "all", p=3, dim=2, nonfaces=0).values
    assert beta1_2 == [1, 0, 1, 0, 0] and beta1_3 == [0, 0, 1, 0, 0]
    assert beta2_2 == [1, 1, 0, 0, 0] and beta2_3 == [0, 1, 0, 0, 0]
    beta0 = ctx.value("simplicial_complexes.betti", family, "all", p=2, dim=0, nonfaces=0).values
    assert beta0 == [1, 1, 1, 1, 2]  # two disjoint edges are the only disconnected member

    # Euler-Poincare: the alternating sum of the Betti numbers is the Euler characteristic.
    for p in (2, 3, 65537):
        graphs = ctx.subsets(edges(6), 5)
        euler = ctx.value("simplicial_complexes.euler_characteristic", graphs, "all", p=p, nonfaces=1).values
        betti = [ctx.value("simplicial_complexes.betti", graphs, "all", p=p, dim=d, nonfaces=1).values
                 for d in range(6)]
        for i, e in enumerate(euler):
            assert sum((-1) ** d * betti[d][i] for d in range(6)) % p == e

    # A simplex is a cone: contractible, and shellable because it has one facet.
    simplex = ctx.explicit(lk.matrix(2, [[[1] * 6]]))
    assert ctx.value("simplicial_complexes.faces", simplex, "all", nonfaces=0).values == [63]
    assert ctx.value("simplicial_complexes.betti", simplex, "all", p=2, dim=0, nonfaces=0).values == [1]
    assert ctx.value("simplicial_complexes.betti", simplex, "all", p=2, dim=1, nonfaces=0).values == [0]
    assert ctx.value("simplicial_complexes.is_shellable", simplex, "all", nonfaces=0).values == [1]

    # Forbidding only the whole vertex set leaves the boundary of the 4-simplex: 2^5 - 2 faces,
    # a 3-sphere, and shellable. Forbidding the empty set (a zero row) leaves nothing at all.
    boundary = ctx.explicit(lk.matrix(2, [[[1, 1, 1, 1, 1]], [[0, 0, 0, 0, 0]]]))
    assert ctx.value("simplicial_complexes.faces", boundary, "all", nonfaces=1).values == [30, 0]
    assert ctx.value("simplicial_complexes.betti", boundary, "all", p=2, dim=0, nonfaces=1).values == [1, 0]
    assert ctx.value("simplicial_complexes.betti", boundary, "all", p=2, dim=3, nonfaces=1).values == [1, 0]
    assert ctx.value("simplicial_complexes.is_shellable", boundary, "all", nonfaces=1).values == [1, 1]

    # Shellable pure complexes have no homology below the top dimension.
    triples = ctx.subsets(uniform(5, 3), 3)
    shellable = ctx.value("simplicial_complexes.is_shellable", triples, "all", nonfaces=0).values
    beta1 = ctx.value("simplicial_complexes.betti", triples, "all", p=2, dim=1, nonfaces=0).values
    sizes = ctx.value("simplicial_complexes.f_count", triples, "all", dim=2, nonfaces=0).values
    for s, b, top in zip(shellable, beta1, sizes):
        if s and top == 3:  # pure two-dimensional: three distinct triangles
            assert b == 0
