"""Oracle and benchmark cases for matrix_groups.

Oracle groups stay below a few dozen elements. The generic backend gets its larger order case from
pairs of 4 x 4 generators, where its stabilizer chain avoids materializing the group.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
import lemmakernel as lk  # noqa: E402
from tools.harness import Case  # noqa: E402

OPS = ["order", "is_irreducible", "is_absolutely_irreducible", "preserves_form", "is_imprimitive"]


def flat(a):
    return [x for row in a for x in row]


def generator_family(ctx, p, matrices, k):
    return ctx.subsets(lk.matrix(p, [flat(a) for a in matrices]), k)


def add_cases(out, name, family, reductions=None):
    for op in OPS:
        args = {"limit": 3} if op != "order" else {}
        out.append(Case(name, family, op, args, reductions=reductions))


def cases(ctx, rng):
    del rng
    I2 = [[1, 0], [0, 1]]
    singer2 = [[0, 1], [1, 1]]
    transvection2 = [[1, 1], [0, 1]]

    out = []
    # Orders 1, 3, and 2. The Singer generator is irreducible but not absolutely irreducible.
    add_cases(out, "F2 single generators", generator_family(ctx, 2, [I2, singer2, transvection2], 1))

    # GL(2,2) is absolutely irreducible and primitive.
    add_cases(out, "GL(2,2)", generator_family(ctx, 2, [singer2, transvection2], 2), ["all"])

    # The signed monomial group has order 8 and permutes the two coordinate lines transitively.
    diagonal3 = [[2, 0], [0, 1]]
    swap3 = [[0, 1], [1, 0]]
    add_cases(out, "monomial degree 2 over F3", generator_family(ctx, 3, [diagonal3, swap3], 2), ["all"])

    # Scalar 2 has order 4 over F5 and preserves no nondegenerate bilinear form.
    add_cases(out, "scalar 2 over F5", generator_family(ctx, 5, [[[2, 0], [0, 2]]], 1), ["all"])

    out += [
        Case("explicit generators", ctx.explicit(lk.matrix(2, [[flat(I2)]])), "order", oracle=False),
        Case("nonsquare dictionary", ctx.subsets(lk.matrix(2, [[1, 0, 0], [0, 1, 0]]), 1), "order", oracle=False),
        Case("singular dictionary", generator_family(ctx, 2, [I2, [[0, 0], [0, 0]]], 1), "order", oracle=False),
    ]

    singer4 = [[0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1], [1, 1, 0, 0]]
    t01 = [[1, 1, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]
    t12 = [[1, 0, 0, 0], [0, 1, 1, 0], [0, 0, 1, 0], [0, 0, 0, 1]]
    t23 = [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 1], [0, 0, 0, 1]]
    cycle4 = [[0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1], [1, 0, 0, 0]]
    out.append(Case(
        "orders of GL4 generator pairs",
        generator_family(ctx, 2, [singer4, t01, t12, t23, cycle4], 2),
        "order",
        bench="histogram",
        oracle=False,
        what="orders of the ten groups generated by pairs from a small GL(4,2) dictionary",
    ))
    return out


def invariants(ctx):
    diagonal3 = [[2, 0], [0, 1]]
    swap3 = [[0, 1], [1, 0]]
    family = generator_family(ctx, 3, [diagonal3, swap3, [[0, 2], [1, 0]]], 2)
    irreducible = ctx.value("matrix_groups.is_irreducible", family).values
    absolute = ctx.value("matrix_groups.is_absolutely_irreducible", family).values
    imprimitive = ctx.value("matrix_groups.is_imprimitive", family).values
    assert all(not a or r for a, r in zip(absolute, irreducible))
    assert all(not b or r for b, r in zip(imprimitive, irreducible))
