/-!
# Runtime reference: objects, families, reductions

What the runtime owns, defined once for every module: matrices over `F_p` and permutations as
lists of naturals, every family kind with its canonical order, the reductions, and the shape of
a result. A module's `Reference.lean` imports this, defines its operations and its value type,
and returns `Lk.Result Value`.

Everything is plain structural recursion so that `decide +kernel` can evaluate it. Nothing here
imports Mathlib; `Lk/Contract.lean` relates these definitions to Mathlib's.
-/

namespace Lk

abbrev Vec := List Nat
abbrev Mat := List Vec
abbrev Perm := List Nat

/-! ## Arithmetic modulo `p` -/

/-- `a ^ e % p` by repeated squaring; `fuel` bounds the recursion (64 covers any `e < 2^64`). -/
def powMod (p a : Nat) : Nat → Nat → Nat
  | 0, _ => 1 % p
  | fuel + 1, e =>
    if e = 0 then 1 % p
    else
      let h := powMod p (a * a % p) fuel (e / 2)
      if e % 2 = 1 then h * a % p else h

/-- Fermat inverse; only used on nonzero entries below a prime. -/
def inv (p a : Nat) : Nat := powMod p a 64 (p - 2)

/-- `row - c * other` entrywise, modulo `p`. -/
def subMul (p : Nat) (row other : Vec) (c : Nat) : Vec :=
  List.zipWith (fun a b => (a + (p - c) * b) % p) row other

def scale (p : Nat) (row : Vec) (c : Nat) : Vec := row.map (fun a => a * c % p)

def matmul (p : Nat) (a b : Mat) : Mat :=
  let cols := (b.headD []).length
  a.map fun row =>
    (List.range cols).map fun j =>
      (List.zipWith (fun x brow => x * brow.getD j 0) row b).foldl (· + ·) 0 % p

def identity (n : Nat) : Mat := (List.range n).map fun i => (List.range n).map fun j => if i = j then 1 else 0

/-! ## Permutations -/

/-- `x ↦ h (g x)`. -/
def compose (g h : Perm) : Perm := g.map fun x => h.getD x 0

def identityPerm (n : Nat) : Perm := List.range n

/-- Insertion sort by a Boolean order. -/
def insertBy (le : α → α → Bool) (x : α) : List α → List α
  | [] => [x]
  | y :: ys => if le x y then x :: y :: ys else y :: insertBy le x ys

def sortBy (le : α → α → Bool) (xs : List α) : List α := xs.foldr (insertBy le) []

def lexLe : List Nat → List Nat → Bool
  | [], _ => true
  | _ :: _, [] => false
  | x :: xs, y :: ys => if x < y then true else if y < x then false else lexLe xs ys

/-- Close `acc` under `step`, one breadth-first layer per unit of fuel, stopping at a fixpoint. -/
def saturate [DecidableEq α] (step : α → List α) : Nat → List α → List α
  | 0, acc => acc
  | fuel + 1, acc =>
    let next := acc.foldl (fun s a => (step a).foldl (fun s b => if b ∈ s then s else s ++ [b]) s) acc
    if next.length = acc.length then acc else saturate step fuel next

/-- Enough layers for any group or orbit a test will ask about. -/
def fuel : Nat := 1 <<< 26

/-- Every element of the permutation group generated by `gens`, lexicographic by image list. -/
def permElements (gens : List Perm) : List Perm :=
  let n := (gens.headD []).length
  sortBy lexLe (saturate (fun g => gens.map (compose g)) fuel [identityPerm n])

/-! ## Families and their canonical order -/

/-- All `k`-element sublists, in lexicographic order of the chosen positions. -/
def combos : List α → Nat → List (List α)
  | _, 0 => [[]]
  | [], _ + 1 => []
  | x :: xs, k + 1 => (combos xs k).map (x :: ·) ++ combos xs (k + 1)

/-- All lists of length `m` over `0..p-1`, lexicographic (first digit slowest). -/
def tuples (p : Nat) : Nat → List (List Nat)
  | 0 => [[]]
  | m + 1 => (List.range p).flatMap fun d => (tuples p m).map (d :: ·)

/-- Split `rows * cols` entries into `rows` rows. -/
def chunk (cols : Nat) : Nat → List Nat → Mat
  | 0, _ => []
  | r + 1, xs => xs.take cols :: chunk cols r (xs.drop cols)

/-- Free positions of the rref shape with pivot columns `piv` (row-major). -/
def freePositions (piv : List Nat) (n : Nat) : List (Nat × Nat) :=
  (List.range piv.length).flatMap fun i =>
    ((List.range n).filter fun c => piv.getD i 0 < c ∧ c ∉ piv).map fun c => (i, c)

def rrefShape (piv : List Nat) (n : Nat) (free : List (Nat × Nat)) (digits : List Nat) : Mat :=
  (List.range piv.length).map fun i => (List.range n).map fun c =>
    if piv.getD i 0 = c then 1
    else match (List.zip free digits).find? fun ((i', c'), _) => i' = i ∧ c' = c with
      | some (_, d) => d
      | none => 0

/-- Every `h`-dimensional subspace of `F_p^n` as its rref basis: pivot sets in lexicographic
order, then free entries in row-major lexicographic order. -/
def grassmannianMembers (p n h : Nat) : List Mat :=
  (combos (List.range n) h).flatMap fun piv =>
    let free := freePositions piv n
    (tuples p free.length).map (rrefShape piv n free)

/-- Every symmetric `n x n` matrix over `F_p`: the upper triangle, row-major, is the base-`p`
expansion of the index. -/
def symmetricMembers (p n : Nat) : List Mat :=
  (tuples p (n * (n + 1) / 2)).map fun digits =>
    -- position of (i, j) with i ≤ j in the row-major upper triangle
    let pos := fun i j => i * n - i * (i - 1) / 2 + (j - i)
    (List.range n).map fun i => (List.range n).map fun j =>
      if i ≤ j then digits.getD (pos i j) 0 else digits.getD (pos j i) 0

/-- The positive integers at most `n`, largest first. -/
def descending (n : Nat) : List Nat := (List.range n).reverse.map (· + 1)

/-- Frequency choices for the available part sizes, largest first. -/
def partitionLists : List Nat → Nat → Nat → Nat → List Vec
  | [], rem, _, _ => if rem = 0 then [[]] else []
  | v :: vs, rem, slots, cap =>
    let maxCount := min cap (min slots (rem / v))
    (List.range (maxCount + 1)).reverse.flatMap fun c =>
      (partitionLists vs (rem - c * v) (slots - c) cap).map fun tail => List.replicate c v ++ tail

/-- Partitions under the runtime constraints, without trailing padding. -/
def constrainedPartitions (total maxPart maxParts maxMultiplicity distinct odd : Nat) : List Vec :=
  let upper := if maxPart = 0 then total else min maxPart total
  let slots := if maxParts = 0 then total else min maxParts total
  let cap := if distinct = 1 then 1 else if maxMultiplicity = 0 then total else maxMultiplicity
  let values := if odd = 1 then (descending upper).filter (· % 2 = 1) else descending upper
  partitionLists values total slots cap

/-- Compositions of `rem` into exactly `parts` positive bounded parts, descending lexicographic. -/
def compositionLists (maxPart rem : Nat) : Nat → List Vec
  | 0 => if rem = 0 then [[]] else []
  | parts + 1 =>
    (descending (min maxPart rem)).flatMap fun x =>
      (compositionLists maxPart (rem - x) parts).map (x :: ·)

inductive Family
  | explicit (p : Nat) (batch : List Mat)
  | subsets (p : Nat) (dictionary : List Vec) (k : Nat)
  | grassmannian (p n h : Nat)
  | allMatrices (p rows cols : Nat)
  | transform (inner : Family) (c : Mat)
  | stack (inner : Family) (rows : Mat)
  | groupElements (gens : List Perm)
  | subsetsOf (inner : Family) (k : Nat)
  | symmetricMatrices (p n : Nat)
  | range (a b : Nat)
  | words (alphabet length : Nat)
  | partitions (total maxPart maxParts maxMultiplicity distinct odd : Nat)
  | compositions (total parts maxPart : Nat)

/-- The prime of a matrix family; 0 for permutations and for natural-number members. -/
def Family.p : Family → Nat
  | .explicit p _ | .subsets p _ _ | .grassmannian p _ _ | .allMatrices p _ _ | .symmetricMatrices p _ => p
  | .transform f _ | .stack f _ | .subsetsOf f _ => f.p
  | .groupElements _ | .range _ _ | .words _ _ | .partitions _ _ _ _ _ _ | .compositions _ _ _ => 0

/-- Members in canonical order. A permutation is a one-row matrix; so is a word, and an integer
is a `1 x 1` matrix. -/
def Family.members : Family → List Mat
  | .explicit _ batch => batch
  | .subsets _ d k => combos d k
  | .grassmannian p n h => grassmannianMembers p n h
  | .allMatrices p rows cols => (tuples p (rows * cols)).map (chunk cols rows)
  | .transform f c => f.members.map fun m => matmul f.p m c
  | .stack f rows => f.members.map (· ++ rows)
  | .groupElements gens => (permElements gens).map ([·])
  | .subsetsOf f k => combos (f.members.map List.flatten) k
  | .symmetricMatrices p n => symmetricMembers p n
  | .range a b => (List.range (b - a)).map fun i => [[a + i]]
  | .words q len => (tuples q len).map ([·])
  | .partitions total maxPart maxParts maxMultiplicity distinct odd =>
    (constrainedPartitions total maxPart maxParts maxMultiplicity distinct odd).map fun xs =>
      [((xs ++ List.replicate total 0).take total)]
  | .compositions total parts maxPart =>
    let maximum := if maxPart = 0 then total else min maxPart total
    let lengths := if parts = 0 then (List.range total).map (· + 1) else [parts]
    lengths.flatMap fun k => (compositionLists maximum total k).map fun xs =>
      [((xs ++ List.replicate total 0).take total)]

/-- The dictionary a `subsets` or `subsets_of` family draws from, for modules whose groups act
on dictionary positions. -/
def Family.dictionary : Family → Option (List Vec)
  | .subsets _ d _ => some d
  | .subsetsOf f _ => some (f.members.map List.flatten)
  | _ => none

def Family.subsetSize : Family → Nat
  | .subsets _ _ k | .subsetsOf _ k => k
  | _ => 0

/-! ## Reductions and results -/

inductive Red
  | all | count | histogram | hits (limit : Nat) | first | sum | max | min

/-- A result: the runtime's own kinds, or a list of module values under `all`. `count` also
carries a `sum`; `first` carries the hit's index and member when there is one; `extremum` the
extreme value, the least index attaining it, and that member. -/
inductive Result (α : Type)
  | integers (xs : List Nat)
  | count (value size : Nat)
  | histogram (size : Nat) (bins : List Nat)
  | hits (size : Nat) (indices : List Nat) (members : List Mat)
  | first (size : Nat) (hit : Option (Nat × Mat))
  | extremum (size value index : Nat) (member : Mat)
  | values (xs : List α)
  | invalid
  deriving DecidableEq, Repr

def histogramOf (xs : List Nat) : List Nat :=
  (List.range (xs.foldl max 0 + 1)).map fun v => (xs.filter (· = v)).length

/-- The extreme value under `better` and the least index attaining it. -/
def extremumOf (better : Nat → Nat → Bool) (ms : List Mat) (xs : List Nat) : Result α :=
  match xs with
  | [] => .invalid
  | x :: rest =>
    let v := rest.foldl (fun acc y => if better y acc then y else acc) x
    let i := xs.idxOf v
    .extremum xs.length v i (ms.getD i [])

def reduceInt (red : Red) (ms : List Mat) (xs : List Nat) : Result α :=
  match red with
  | .all => .integers xs
  | .histogram => .histogram xs.length (histogramOf xs)
  | .sum => .count (xs.foldl (· + ·) 0) xs.length
  | .max => extremumOf (· > ·) ms xs
  | .min => extremumOf (· < ·) ms xs
  | _ => .invalid

def reduceBool (red : Red) (ms : List Mat) (flags : List Bool) : Result α :=
  let idx := ((List.range flags.length).zip flags).filterMap fun (i, b) => if b then some i else none
  match red with
  | .all => .integers (flags.map fun b => if b then 1 else 0)
  | .count => .count (flags.filter id).length flags.length
  | .hits limit => .hits flags.length idx ((idx.take limit).map fun i => ms.getD i [])
  | .first => .first flags.length (idx.head?.map fun i => (i, ms.getD i []))
  | _ => .invalid

/-- A per-member value is only ever materialised. -/
def reduceValues (red : Red) (xs : List α) : Result α :=
  match red with
  | .all => .values xs
  | _ => .invalid

end Lk
