/-!
# Runtime reference: objects, families, reductions

What the runtime owns, defined once for every module: matrices over `F_p` and permutations as
lists of naturals, every family kind with its canonical order, the reductions, and the shape of
a result. A module's `Reference.lean` imports this, defines its operations and its value type,
and returns `Lk.Result Value`.

Everything is plain structural recursion so that `decide +kernel` can evaluate it. Nothing here
imports Mathlib; `Lk/Contract.lean` relates these definitions to Mathlib's.
-/

namespace Lk

abbrev Vec := List Nat
abbrev Mat := List Vec
abbrev Perm := List Nat

/-! ## Arithmetic modulo `p` -/

/-- `a ^ e % p` by repeated squaring; `fuel` bounds the recursion (64 covers any `e < 2^64`). -/
def powMod (p a : Nat) : Nat → Nat → Nat
  | 0, _ => 1 % p
  | fuel + 1, e =>
    if e = 0 then 1 % p
    else
      let h := powMod p (a * a % p) fuel (e / 2)
      if e % 2 = 1 then h * a % p else h

/-- Fermat inverse; only used on nonzero entries below a prime. -/
def inv (p a : Nat) : Nat := powMod p a 64 (p - 2)

/-- `row - c * other` entrywise, modulo `p`. -/
def subMul (p : Nat) (row other : Vec) (c : Nat) : Vec :=
  List.zipWith (fun a b => (a + (p - c) * b) % p) row other

def scale (p : Nat) (row : Vec) (c : Nat) : Vec := row.map (fun a => a * c % p)

def matmul (p : Nat) (a b : Mat) : Mat :=
  let cols := (b.headD []).length
  a.map fun row =>
    (List.range cols).map fun j =>
      (List.zipWith (fun x brow => x * brow.getD j 0) row b).foldl (· + ·) 0 % p

def identity (n : Nat) : Mat := (List.range n).map fun i => (List.range n).map fun j => if i = j then 1 else 0

/-! ## Permutations -/

/-- `x ↦ h (g x)`. -/
def compose (g h : Perm) : Perm := g.map fun x => h.getD x 0

def identityPerm (n : Nat) : Perm := List.range n

/-- Insertion sort by a Boolean order. -/
def insertBy (le : α → α → Bool) (x : α) : List α → List α
  | [] => [x]
  | y :: ys => if le x y then x :: y :: ys else y :: insertBy le x ys

def sortBy (le : α → α → Bool) (xs : List α) : List α := xs.foldr (insertBy le) []

def lexLe : List Nat → List Nat → Bool
  | [], _ => true
  | _ :: _, [] => false
  | x :: xs, y :: ys => if x < y then true else if y < x then false else lexLe xs ys

/-- Close `acc` under `step`, one breadth-first layer per unit of fuel, stopping at a fixpoint. -/
def saturate [DecidableEq α] (step : α → List α) : Nat → List α → List α
  | 0, acc => acc
  | fuel + 1, acc =>
    let next := acc.foldl (fun s a => (step a).foldl (fun s b => if b ∈ s then s else s ++ [b]) s) acc
    if next.length = acc.length then acc else saturate step fuel next

/-- Enough layers for any group or orbit a test will ask about. -/
def fuel : Nat := 1 <<< 26

/-- Every element of the permutation group generated by `gens`, lexicographic by image list. -/
def permElements (gens : List Perm) : List Perm :=
  let n := (gens.headD []).length
  sortBy lexLe (saturate (fun g => gens.map (compose g)) fuel [identityPerm n])

/-! ## Families and their canonical order -/

/-- All `k`-element sublists, in lexicographic order of the chosen positions. -/
def combos : List α → Nat → List (List α)
  | _, 0 => [[]]
  | [], _ + 1 => []
  | x :: xs, k + 1 => (combos xs k).map (x :: ·) ++ combos xs (k + 1)

/-- All lists of length `m` over `0..p-1`, lexicographic (first digit slowest). -/
def tuples (p : Nat) : Nat → List (List Nat)
  | 0 => [[]]
  | m + 1 => (List.range p).flatMap fun d => (tuples p m).map (d :: ·)

/-- Split `rows * cols` entries into `rows` rows. -/
def chunk (cols : Nat) : Nat → List Nat → Mat
  | 0, _ => []
  | r + 1, xs => xs.take cols :: chunk cols r (xs.drop cols)

/-- Free positions of the rref shape with pivot columns `piv` (row-major). -/
def freePositions (piv : List Nat) (n : Nat) : List (Nat × Nat) :=
  (List.range piv.length).flatMap fun i =>
    ((List.range n).filter fun c => piv.getD i 0 < c ∧ c ∉ piv).map fun c => (i, c)

def rrefShape (piv : List Nat) (n : Nat) (free : List (Nat × Nat)) (digits : List Nat) : Mat :=
  (List.range piv.length).map fun i => (List.range n).map fun c =>
    if piv.getD i 0 = c then 1
    else match (List.zip free digits).find? fun ((i', c'), _) => i' = i ∧ c' = c with
      | some (_, d) => d
      | none => 0

/-- Every `h`-dimensional subspace of `F_p^n` as its rref basis: pivot sets in lexicographic
order, then free entries in row-major lexicographic order. -/
def grassmannianMembers (p n h : Nat) : List Mat :=
  (combos (List.range n) h).flatMap fun piv =>
    let free := freePositions piv n
    (tuples p free.length).map (rrefShape piv n free)

inductive Family
  | explicit (p : Nat) (batch : List Mat)
  | subsets (p : Nat) (dictionary : List Vec) (k : Nat)
  | grassmannian (p n h : Nat)
  | allMatrices (p rows cols : Nat)
  | transform (inner : Family) (c : Mat)
  | stack (inner : Family) (rows : Mat)
  | groupElements (gens : List Perm)

/-- The prime of a matrix family; 0 for permutations. -/
def Family.p : Family → Nat
  | .explicit p _ | .subsets p _ _ | .grassmannian p _ _ | .allMatrices p _ _ => p
  | .transform f _ | .stack f _ => f.p
  | .groupElements _ => 0

/-- Members in canonical order. A permutation is a one-row matrix. -/
def Family.members : Family → List Mat
  | .explicit _ batch => batch
  | .subsets _ d k => combos d k
  | .grassmannian p n h => grassmannianMembers p n h
  | .allMatrices p rows cols => (tuples p (rows * cols)).map (chunk cols rows)
  | .transform f c => f.members.map fun m => matmul f.p m c
  | .stack f rows => f.members.map (· ++ rows)
  | .groupElements gens => (permElements gens).map ([·])

/-! ## Reductions and results -/

inductive Red
  | all | count | histogram | hits (limit : Nat)

/-- A result: the runtime's own kinds, or a list of module values under `all`. -/
inductive Result (α : Type)
  | integers (xs : List Nat)
  | count (value size : Nat)
  | histogram (size : Nat) (bins : List Nat)
  | hits (size : Nat) (indices : List Nat) (members : List Mat)
  | values (xs : List α)
  | invalid
  deriving DecidableEq, Repr

def histogramOf (xs : List Nat) : List Nat :=
  (List.range (xs.foldl max 0 + 1)).map fun v => (xs.filter (· = v)).length

def reduceInt (red : Red) (xs : List Nat) : Result α :=
  match red with
  | .all => .integers xs
  | .histogram => .histogram xs.length (histogramOf xs)
  | _ => .invalid

def reduceBool (red : Red) (ms : List Mat) (flags : List Bool) : Result α :=
  match red with
  | .all => .integers (flags.map fun b => if b then 1 else 0)
  | .count => .count (flags.filter id).length flags.length
  | .hits limit =>
    let idx := ((List.range flags.length).zip flags).filterMap fun (i, b) => if b then some i else none
    .hits flags.length idx ((idx.take limit).map fun i => ms.getD i [])
  | .histogram => .invalid

/-- A per-member value is only ever materialised. -/
def reduceValues (red : Red) (xs : List α) : Result α :=
  match red with
  | .all => .values xs
  | _ => .invalid

end Lk
