#!/usr/bin/env python3
"""Generate the stored catalogue of all groups of order n, for n up to a bound.

The runtime's `group_catalogue(n)` family serves one table per isomorphism class of groups of
order n. This script is where those tables come from: it enumerates the classes, canonicalises
each one, sorts them, checks the counts against the classification of small groups, and writes
`runtime/src/group_catalogue_data.cpp`.

Enumeration. Every group of order below 60 is solvable, so it has a normal subgroup N of prime
index p, and is then determined by N, the automorphism a = conjugation by a transversal element
t, and c = t^p in N, subject to a(c) = c and a^p = conjugation by c. Multiplication on N x Z_p is

    (x, i) (y, j) = (x a^i(y) c^[i+j>=p], (i + j) mod p).

So the groups of order n are found from the (already enumerated) groups of order n/p, one prime
divisor p at a time. The construction produces every group of order n at least once and nothing
else; duplicates are removed by canonical form.

Canonical form. Element labels are chosen to make every top-left corner of the table least: the
identity is 0, label k goes to whichever element keeps the (k+1) x (k+1) corner lexicographically
least once the k x k corner is fixed, and a product of labelled elements takes the smallest unused
label as the corner first shows it. Reading corner by corner rather than row by row judges a
labelling on the part of the group it has already named, which is what makes the search cheap.
The catalogue for one order lists these canonical tables in increasing lexicographic order, so the
file depends on nothing but mathematics.

Usage: tools/group_catalogue.py [--max-order N] [--check-only] [--out PATH]
"""
from __future__ import annotations

import argparse
import itertools
import sys
import time
from pathlib import Path

# Number of groups of each order, from the classification of small groups (OEIS A000001).
KNOWN_COUNTS = [
    0, 1, 1, 1, 2, 1, 2, 1, 5, 2, 2, 1, 5, 1, 2, 1, 14, 1, 5, 1, 5,
    2, 2, 1, 15, 2, 2, 5, 4, 1, 4, 1, 51, 1, 2, 1, 14, 1, 2, 2, 14,
]


# ---- basic table arithmetic ---------------------------------------------------------------------

def identity_of(t):
    n = len(t)
    for e in range(n):
        if all(t[e][x] == x and t[x][e] == x for x in range(n)):
            return e
    raise ValueError("table has no identity")


def inverses_of(t):
    n, e = len(t), identity_of(t)
    out = [None] * n
    for x in range(n):
        for y in range(n):
            if t[x][y] == e:
                out[x] = y
                break
        if out[x] is None:
            raise ValueError("table has no inverse for %d" % x)
    return out


def is_group(t):
    """The full group axioms, used on the tables that reach the catalogue."""
    n = len(t)
    if n == 0 or any(len(row) != n for row in t):
        return False
    if any(x >= n for row in t for x in row):
        return False
    for i in range(n):
        if sorted(t[i]) != list(range(n)) or sorted(t[x][i] for x in range(n)) != list(range(n)):
            return False
    try:
        identity_of(t)
        inverses_of(t)
    except ValueError:
        return False
    return all(t[t[a][b]][c] == t[a][t[b][c]]
               for a in range(n) for b in range(n) for c in range(n))


def element_orders(t):
    n, e = len(t), identity_of(t)
    out = [0] * n
    for x in range(n):
        y, k = x, 1
        while y != e:
            y, k = t[y][x], k + 1
        out[x] = k
    return out


def closure(t, generators):
    """The subgroup generated by `generators`, as a sorted tuple of labels."""
    e = identity_of(t)
    seen = {e}
    queue = [e]
    for x in queue:
        for g in generators:
            y = t[x][g]
            if y not in seen:
                seen.add(y)
                queue.append(y)
    return tuple(sorted(seen))


def generating_sequence(t):
    """A short generating sequence: repeatedly add the least element outside the closure."""
    n = len(t)
    gens, sub = [], closure(t, [])
    while len(sub) < n:
        for x in range(n):
            if x not in sub:
                gens.append(x)
                break
        sub = closure(t, gens)
    return gens


def words_over(t, gens):
    """For every element, one word in `gens` (as a list of generator indices) reaching it."""
    e = identity_of(t)
    word = {e: ()}
    queue = [e]
    for x in queue:
        for i, g in enumerate(gens):
            y = t[x][g]
            if y not in word:
                word[y] = word[x] + (i,)
                queue.append(y)
    return [word[x] for x in range(len(t))]


def isomorphisms(a, b, want_all):
    """Isomorphisms a -> b, found by mapping a generating sequence and propagating products.

    Fixing the image of one element forces the image of its product with every element already
    mapped, so the search visits little beyond the isomorphisms themselves. With `want_all` false
    it stops at the first one.
    """
    n = len(a)
    if n != len(b):
        return []
    orders_a, orders_b = element_orders(a), element_orders(b)
    gens = generating_sequence(a)
    phi = [-1] * n
    pre = [-1] * n
    known: list[int] = []
    out = []

    def assign(x, y):
        queue = [(x, y)]
        while queue:
            u, v = queue.pop()
            if phi[u] != -1:
                if phi[u] != v:
                    return False
                continue
            if pre[v] != -1 or orders_a[u] != orders_b[v]:
                return False
            phi[u] = v
            pre[v] = u
            known.append(u)
            for w in known:
                queue.append((a[u][w], b[v][phi[w]]))
                queue.append((a[w][u], b[phi[w]][v]))
        return True

    def undo(mark):
        while len(known) > mark:
            u = known.pop()
            pre[phi[u]] = -1
            phi[u] = -1

    def search(i):
        if out and not want_all:
            return
        if i == len(gens):
            if len(known) == n:
                out.append(tuple(phi))
            return
        g = gens[i]
        if phi[g] != -1:
            search(i + 1)
            return
        for y in range(n):
            if pre[y] == -1 and orders_b[y] == orders_a[g]:
                mark = len(known)
                if assign(g, y):
                    search(i + 1)
                undo(mark)

    assign(identity_of(a), identity_of(b))
    search(0)
    return out


def automorphisms(t):
    """Every automorphism of the table, as a tuple image[x]."""
    return isomorphisms(t, t, True)


# ---- canonical form ------------------------------------------------------------------------------

def corner_cells(n):
    """The table's cells in the order that grows the top-left corner one row and column at a time.

    Comparing two tables cell by cell in this order compares their 1x1 corners, then their 2x2
    corners, and so on, so a labelling is judged on the part of the group it has named already.
    """
    cells = [(0, 0)]
    for k in range(1, n):
        cells += [(i, k) for i in range(k)]
        cells += [(k, j) for j in range(k + 1)]
    return cells


def canonical(t):
    """The table whose nested top-left corners are least over all relabellings of the group.

    The identity takes label 0, and reading the table corner by corner decides the rest: label k
    goes to the element that keeps the (k+1) x (k+1) corner least, and every product of labelled
    elements takes the smallest unused label as the corner first shows it. The search carries all
    labellings that still tie, so a cell where one of them is larger drops it immediately, and it
    keeps one element per orbit of the automorphisms fixing every labelled element, since those
    complete to the same table.
    """
    n = len(t)
    e = identity_of(t)
    if n == 1:
        return ((0,),)

    auts = automorphisms(t)
    start = [-1] * n
    start[e] = 0
    states = [([e], start, auts)]      # elements by label, labels by element, stabiliser

    for i, j in corner_cells(n):
        while any(max(i, j) >= len(elem) for elem, _, _ in states):
            grown = []
            for elem, label, stab in states:
                if max(i, j) < len(elem):
                    grown.append((elem, label, stab))
                    continue
                k, seen = len(elem), set()
                for y in range(n):
                    if label[y] >= 0 or y in seen:
                        continue
                    seen.update(s[y] for s in stab)
                    labels = label[:]
                    labels[y] = k
                    grown.append((elem + [y], labels, [s for s in stab if s[y] == y]))
            states = grown
        least, survivors = n, []
        for elem, label, stab in states:
            product = t[elem[i]][elem[j]]
            entry = label[product] if label[product] >= 0 else len(elem)
            if entry > least:
                continue
            if entry < least:
                least, survivors = entry, []
            survivors.append((elem, label, stab, product, label[product] < 0))
        states = []
        for elem, label, stab, product, fresh in survivors:
            if fresh:
                labels = label[:]
                labels[product] = least
                states.append((elem + [product], labels, stab))
            else:
                states.append((elem, label, stab))

    elem, label, _ = states[0]
    return tuple(tuple(label[t[elem[a]][elem[b]]] for b in range(n)) for a in range(n))


# ---- invariants used to keep the deduplication cheap ---------------------------------------------

def fingerprint(t):
    n = len(t)
    inv = inverses_of(t)
    orders = element_orders(t)
    centralizers = [sum(1 for g in range(n) if t[g][x] == t[x][g]) for x in range(n)]
    classes = sorted(n // c for c in centralizers)
    centre = sum(1 for x in range(n) if centralizers[x] == n)
    derived = closure(t, [t[t[t[inv[x]][inv[y]]][x]][y] for x in range(n) for y in range(n)])
    return (n, tuple(sorted(orders)), tuple(classes), centre, len(derived),
            tuple(sorted(zip(orders, centralizers))))


def isomorphic(a, b):
    """Whether two tables of the same order present isomorphic groups."""
    return bool(isomorphisms(a, b, False))


# ---- enumeration ---------------------------------------------------------------------------------

def prime_divisors(n):
    out, d, m = [], 2, n
    while d * d <= m:
        if m % d == 0:
            out.append(d)
            while m % d == 0:
                m //= d
        d += 1
    if m > 1:
        out.append(m)
    return out


def conjugacy_representatives(group):
    """One permutation from each conjugacy class of a group of permutations, given in full.

    Conjugate automorphisms give isomorphic extensions, so the enumeration only needs these.
    """
    n = len(group[0])
    index = {g: i for i, g in enumerate(group)}
    seen = [False] * len(group)
    out = []
    for i, a in enumerate(group):
        if seen[i]:
            continue
        out.append(a)
        for g in group:
            ginv = [0] * n
            for x in range(n):
                ginv[g[x]] = x
            seen[index[tuple(g[a[ginv[x]]] for x in range(n))]] = True
    return out


def extensions(t, p):
    """Every group with normal subgroup `t` of index `p`, as a raw table of order p*|t|."""
    m = len(t)
    inv = inverses_of(t)
    for alpha in conjugacy_representatives(automorphisms(t)):
        powers = [tuple(range(m))]
        for _ in range(p):
            previous = powers[-1]
            powers.append(tuple(alpha[previous[x]] for x in range(m)))
        alpha_p = powers[p]
        for c in range(m):
            if alpha[c] != c:
                continue
            if any(alpha_p[x] != t[t[c][x]][inv[c]] for x in range(m)):
                continue
            n = m * p
            table = [[0] * n for _ in range(n)]
            for i in range(p):
                for j in range(p):
                    carry = i + j >= p
                    k = (i + j) % p
                    for x in range(m):
                        for y in range(m):
                            z = t[x][powers[i][y]]
                            if carry:
                                z = t[z][c]
                            table[i * m + x][j * m + y] = k * m + z
            yield tuple(tuple(row) for row in table)


def groups_of_order(n, smaller):
    """Canonical tables of every group of order n, given the catalogue of smaller orders."""
    if n == 1:
        return [((0,),)]
    buckets: dict[tuple, list[tuple]] = {}
    representatives = []
    for p in prime_divisors(n):
        for base in smaller[n // p]:
            for table in extensions(base, p):
                key = fingerprint(table)
                bucket = buckets.setdefault(key, [])
                if any(isomorphic(table, seen) for seen in bucket):
                    continue
                bucket.append(table)
                representatives.append(table)
    return sorted(canonical(table) for table in representatives)


def build(max_order, verbose=True):
    catalogue = {}
    for n in range(1, max_order + 1):
        start = time.time()
        tables = groups_of_order(n, catalogue)
        catalogue[n] = tables
        expected = KNOWN_COUNTS[n] if n < len(KNOWN_COUNTS) else None
        if expected is not None and len(tables) != expected:
            raise SystemExit(f"order {n}: enumerated {len(tables)} groups, classification says {expected}")
        for table in tables:
            if not is_group(table):
                raise SystemExit(f"order {n}: a catalogue table is not a group")
        if verbose:
            print(f"order {n:>3}: {len(tables):>3} groups  ({time.time() - start:.1f}s)", flush=True)
    return catalogue


# ---- output ----------------------------------------------------------------------------------------

HEADER = """/* Groups of small order as multiplication tables, one per isomorphism class.
 *
 * Generated by tools/group_catalogue.py; do not edit. Labels make every top-left corner of a
 * table least over all relabellings of its group, so label 0 is the identity, and the tables of
 * one order are listed in increasing lexicographic order. The generator enumerates the classes
 * itself, extending each group of order n/p by a cyclic group of prime order p, and checks the
 * counts against the classification of small groups.
 */
#include "family.hpp"

namespace lk {

"""


def emit(catalogue, path):
    orders = sorted(catalogue)
    entries = []
    offsets = [0]
    counts = []
    for n in orders:
        counts.append(len(catalogue[n]))
        for table in catalogue[n]:
            for row in table:
                entries.extend(row)
        offsets.append(len(entries))

    lines = [HEADER]
    lines.append("/* Number of groups of order 1, 2, ... %d. */\n" % orders[-1])
    lines.append("const uint8_t group_catalogue_counts[%d] = {\n" % len(counts))
    lines.append(wrap(counts, 20))
    lines.append("};\n\n")
    lines.append("/* Where order n's tables start in group_catalogue_entries, for n = 1, 2, ... */\n")
    lines.append("const uint32_t group_catalogue_offsets[%d] = {\n" % len(offsets))
    lines.append(wrap(offsets, 12))
    lines.append("};\n\n")
    lines.append("/* Every table of order 1, then of order 2, and so on, row-major. */\n")
    lines.append("const uint8_t group_catalogue_entries[%d] = {\n" % len(entries))
    lines.append(wrap(entries, 32))
    lines.append("};\n\n")
    lines.append("const uint64_t group_catalogue_max_order = %d;\n\n} // namespace lk\n" % orders[-1])
    path.write_text("".join(lines))


def wrap(values, per_line):
    out = []
    for i in range(0, len(values), per_line):
        out.append("    " + ", ".join(str(v) for v in values[i:i + per_line]) + ",\n")
    return "".join(out)


def main():
    root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--max-order", type=int, default=31)
    parser.add_argument("--out", type=Path, default=root / "runtime/src/group_catalogue_data.cpp")
    parser.add_argument("--check-only", action="store_true",
                        help="enumerate and check the counts without writing the data file")
    args = parser.parse_args()
    catalogue = build(args.max_order)
    if args.check_only:
        return 0
    emit(catalogue, args.out)
    total = sum(len(v) for v in catalogue.values())
    print(f"wrote {args.out} with {total} groups of order at most {args.max_order}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
