#!/usr/bin/env python3
"""Generate everything that derives from module manifests, or check that it is current.

    tools/manifest.py generate     rewrite runtime/generated/*, python/lemmakernel/_manifest.py, lakefile.toml
    tools/manifest.py check        exit 1 if any generated file is stale or a module is incomplete

modules/<name>/manifest.toml is the single declaration of a module. This script is the only
producer of the C++ registry data, the runtime description JSON, the CMake source list, the Lake
configuration and the Python-side manifest.
"""
from __future__ import annotations

import json
import pprint
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MODULES = ROOT / "modules"
RUNTIME_MANIFEST = ROOT / "runtime" / "manifest.toml"
GENERATED_CPP = ROOT / "runtime" / "generated" / "manifest.cpp"
GENERATED_CMAKE = ROOT / "runtime" / "generated" / "modules.cmake"
GENERATED_PY = ROOT / "python" / "lemmakernel" / "_manifest.py"
GENERATED_LAKE = ROOT / "lakefile.toml"

REQUIRED_FILES = ("lean", "contract", "reference", "naive", "bench", "tests")
FEATURE_FLAGS = {
    "avx512bw": ["-mavx512f", "-mavx512bw", "-mavx512vl", "-mavx512dq"],
}


def load_modules() -> list[dict]:
    out = []
    for manifest in sorted(MODULES.glob("*/manifest.toml")):
        data = tomllib.loads(manifest.read_text())
        data["_dir"] = manifest.parent
        if data["module"]["name"] != manifest.parent.name:
            raise SystemExit(f"{manifest}: module name {data['module']['name']!r} != directory {manifest.parent.name!r}")
        out.append(data)
    return out


def load_runtime() -> dict:
    return tomllib.loads(RUNTIME_MANIFEST.read_text())


def validate(runtime: dict, modules: list[dict]) -> list[str]:
    problems = []
    reductions = {r["name"]: r for r in runtime.get("reductions", [])}
    for m in modules:
        if "reductions" in m:
            problems.append(f"{m['module']['name']}: reductions are declared in runtime/manifest.toml, not per module")
        name = m["module"]["name"]
        for key in REQUIRED_FILES:
            rel = m["module"].get(key)
            if not rel:
                problems.append(f"{name}: manifest lacks module.{key}")
            elif not (m["_dir"] / rel).exists():
                problems.append(f"{name}: {key} file {rel} does not exist")
        lean_root = m["_dir"] / m["module"].get("lean", "lean") / (lean_lib(name) + ".lean")
        if not lean_root.exists():
            problems.append(f"{name}: Lean root module {lean_root.relative_to(ROOT)} does not exist")
        for b in m.get("backends", []):
            for src in b["sources"]:
                if not (m["_dir"] / src).exists():
                    problems.append(f"{name}: backend {b['name']} source {src} does not exist")
            for feature in b.get("requires", []):
                if feature not in FEATURE_FLAGS:
                    problems.append(f"{name}: backend {b['name']} requires unknown feature {feature}")
        values = {k["name"] for k in m.get("kinds", [])} | {"integer", "boolean"} | {k["name"] for mm in modules for k in mm.get("kinds", [])}
        family_names = {f["name"] for mm in modules for f in mm.get("families", [])}
        for op in m.get("operations", []):
            for fam in op.get("families", []):
                if fam not in family_names:
                    problems.append(f"{name}: operation {op['name']} restricts to unknown family {fam}")
            if op["value"] not in values:
                problems.append(f"{name}: operation {op['name']} has unknown value type {op['value']}")
            if not any(op["value"] in r["accepts"] or "*" in r["accepts"] for r in reductions.values()):
                problems.append(f"{name}: no reduction accepts operation {op['name']}")
    return problems


def lean_lib(module: str) -> str:
    return module[:1].upper() + module[1:]


def render_lakefile(modules: list[dict]) -> str:
    lines = ["# Generated by tools/manifest.py from modules/*/manifest.toml. Do not edit.",
             "# One Lake library per module: its contract (against Mathlib) and executable reference.",
             'name = "LemmaKernel"',
             f"defaultTargets = {json.dumps([lean_lib(m['module']['name']) for m in modules])}",
             "", "[[require]]", 'name = "mathlib"', 'scope = "leanprover-community"', 'rev = "v4.33.0"']
    for m in modules:
        name = m["module"]["name"]
        src = (m["_dir"] / m["module"]["lean"]).relative_to(ROOT).as_posix()
        lines += ["", "[[lean_lib]]", f'name = "{lean_lib(name)}"', f'srcDir = "{src}"', f'roots = ["{lean_lib(name)}"]']
    return "\n".join(lines) + "\n"


def cstr(s: str) -> str:
    return json.dumps(s)


def c_array(name: str, items: list[str]) -> str:
    body = ", ".join(cstr(i) for i in items)
    return f"static const char *const {name}[] = {{{body}{', ' if items else ''}nullptr}};\n"


def render_cpp(runtime: dict, modules: list[dict]) -> str:
    lines = ["// Generated by tools/manifest.py from modules/*/manifest.toml. Do not edit.",
             '#include "../src/registry.hpp"', "", "namespace lk {", "namespace {", ""]
    ops, reds, backs = [], [], []
    for m in modules:
        mod = m["module"]["name"]
        for op in m.get("operations", []):
            arr = f"args_{mod}_{op['name']}"
            lines.append(c_array(arr, op.get("args", [])))
            fams = f"families_{mod}_{op['name']}"
            lines.append(c_array(fams, op.get("families", [])))
            ops.append(f"    {{{cstr(mod)}, {cstr(op['name'])}, {cstr(op['value'])}, {arr}, {fams}}},")
        for b in m.get("backends", []):
            req = f"requires_{mod}_{b['name']}"
            lines.append(c_array(req, b.get("requires", [])))
            backs.append(f"    {{{cstr(mod)}, {cstr(b['name'])}, {req}}},")
    for r in runtime.get("reductions", []):
        acc = f"accepts_{r['name']}"
        arg = f"redargs_{r['name']}"
        lines.append(c_array(acc, r["accepts"]))
        lines.append(c_array(arg, r.get("args", [])))
        reds.append(f"    {{{cstr(r['name'])}, {acc}, {arg}}},")
    lines += ["} // namespace", "",
              "const std::vector<ManifestOperation> &manifest_operations() {",
              "    static const std::vector<ManifestOperation> v{", *ops, "    };", "    return v;", "}", "",
              "const std::vector<ManifestReduction> &manifest_reductions() {",
              "    static const std::vector<ManifestReduction> v{", *reds, "    };", "    return v;", "}", "",
              "const std::vector<ManifestBackend> &manifest_backends() {",
              "    static const std::vector<ManifestBackend> v{", *backs, "    };", "    return v;", "}", ""]
    public = []
    for m in modules:
        entry = {k: v for k, v in m.items() if not k.startswith("_")}
        public.append(entry)
    describe = json.dumps({"runtime": runtime, "modules": public}, indent=None, sort_keys=True)
    lines += ["const char *manifest_describe_json() {", f"    return {cstr(describe)};", "}", "", "} // namespace lk", ""]
    return "\n".join(lines)


def render_cmake(modules: list[dict]) -> str:
    lines = ["# Generated by tools/manifest.py from modules/*/manifest.toml. Do not edit.", ""]
    for m in modules:
        mod = m["module"]["name"]
        for b in m.get("backends", []):
            for src in b["sources"]:
                path = (m["_dir"] / src).relative_to(ROOT).as_posix()
                lines.append(f"target_sources(lemmakernel PRIVATE ${{CMAKE_SOURCE_DIR}}/{path})")
                flags = [f for feat in b.get("requires", []) for f in FEATURE_FLAGS[feat]]
                if flags:
                    lines.append(f"set_source_files_properties(${{CMAKE_SOURCE_DIR}}/{path} PROPERTIES COMPILE_OPTIONS \"{';'.join(flags)}\")")
        lines.append(f"# module {mod}: backends {[b['name'] for b in m.get('backends', [])]}")
    return "\n".join(lines) + "\n"


def render_python(runtime: dict, modules: list[dict]) -> str:
    public = [{k: v for k, v in m.items() if not k.startswith("_")} for m in modules]
    return ("# Generated by tools/manifest.py from runtime/manifest.toml and modules/*/manifest.toml. Do not edit.\n"
            f"RUNTIME = {pprint.pformat(runtime, width=110, sort_dicts=True)}\n"
            f"MODULES = {pprint.pformat(public, width=110, sort_dicts=True)}\n")


def outputs(runtime: dict, modules: list[dict]) -> dict[Path, str]:
    return {GENERATED_CPP: render_cpp(runtime, modules), GENERATED_CMAKE: render_cmake(modules),
            GENERATED_PY: render_python(runtime, modules), GENERATED_LAKE: render_lakefile(modules)}


def main(argv: list[str]) -> int:
    mode = argv[1] if len(argv) > 1 else "check"
    runtime = load_runtime()
    modules = load_modules()
    problems = validate(runtime, modules)
    if problems:
        print("\n".join(problems))
        return 1
    files = outputs(runtime, modules)
    if mode == "generate":
        for path, text in files.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
        print(f"generated {len(files)} files for {len(modules)} module(s)")
        return 0
    if mode == "check":
        stale = [str(p.relative_to(ROOT)) for p, text in files.items() if not p.exists() or p.read_text() != text]
        if stale:
            print("stale generated files (run tools/manifest.py generate): " + ", ".join(stale))
            return 1
        print(f"manifests consistent: {', '.join(m['module']['name'] for m in modules)}")
        return 0
    print(__doc__)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
