import Mathlib
import Burnside.Reference
import Lk.Contract

/-!
# burnside: contract

The permutation group acts on dictionary positions of subset families and coordinate positions of
word families. The declarations below connect the executable cycle formulas to Mathlib's finite
permutations, fixed-point sets, and orbit quotient. The proofs are open obligations.
-/

namespace Burnside.Contract

open Lk

/-- The list permutation as a Mathlib permutation. The well-formedness hypothesis on callers
licenses this conversion. -/
noncomputable def asPerm {n : Nat} (g : Perm) : Equiv.Perm (Fin n) := by
  sorry

/-- Number of cycles of exactly `length` in a finite permutation. -/
noncomputable def cycleCount {n : Nat} (g : Equiv.Perm (Fin n)) (length : Nat) : Nat := by
  sorry

/-- The induced permutation of family indices. For subsets it permutes chosen dictionary
positions; for words it moves coordinates. -/
noncomputable def actionElement (f : Family) (g : Perm) : Equiv.Perm (Fin f.members.length) := by
  sorry

/-- The subgroup of permutations of family indices generated by the supplied group. -/
noncomputable def actionGroup (f : Family) (group : Orbits.Group) :
    Subgroup (Equiv.Perm (Fin f.members.length)) := by
  sorry

/-- The executable cycle-count vector agrees with the cycle decomposition of a Mathlib
permutation. -/
theorem cycleType_spec {n : Nat} (g : Perm) (hg : validPerm n g = true) (length : Nat)
    (hlower : 1 ≤ length) (hupper : length ≤ n) :
    (cycleType g).getD (length - 1) 0 = cycleCount (n := n) (asPerm (n := n) g) length := by
  sorry

/-- `fixed_count` is the cardinality of the fixed-point set of the induced action. -/
theorem fixedCount_spec (f : Family) (g : Perm) (c : Nat)
    (h : run (.fixedCount [g]) f .all = .values [.count c]) :
    c = Fintype.card {i : Fin f.members.length // actionElement f g i = i} := by
  sorry

/-- `orbit_count` is the cardinality of Mathlib's orbit quotient for the generated action. -/
theorem orbitCount_spec (f : Family) (group : Orbits.Group) (c : Nat)
    (h : run (.orbitCount group) f .all = .values [.count c]) :
    c = Nat.card (MulAction.orbitRel.Quotient (actionGroup f group) (Fin f.members.length)) := by
  sorry

/-- `cycle_index` has denominator `|G|`; the multiplicity beside a cycle-count vector is the
number of group elements with that vector. Together with `cycleType_spec`, this is the usual
cycle index of the Mathlib permutations. -/
theorem cycleIndex_spec (f : Family) (group : Orbits.Group) (elements : List Perm)
    (hgroup : groupElements f group = some elements) :
    run (.cycleIndex group) f .all =
      .values ((cycleIndexTerms elements).map fun t => .cycleIndexTerm t) := by
  sorry

end Burnside.Contract
